import type { VocabGroupDef, VocabTier, ActivityType, WordData } from './types';
import { CEFR_LEVEL_ORDER } from './constants';
import { WORDS } from './words';

export const TIER_ORDER: VocabTier[] = ['easy', 'easy-medium', 'medium', 'medium-hard', 'hard'];

// ── Tier activity type presets ────────────────────────────────────────────
const TOPIC_ACTIVITIES: ActivityType[] = [
  'definitions',
  'synonyms',
  'antonyms',
  'collocations',
  'fill-blank',
  'word-assoc',
  'vocab-exercise',
  'exercise',
];

const SYNONYM_ACTIVITIES: ActivityType[] = [
  'definitions',
  'antonyms',
  'collocations',
  'fill-blank',
  'word-assoc',
  'vocab-exercise',
];

// ── 82 Group Definitions ──────────────────────────────────────────────────

export const VOCAB_GROUP_DEFS: VocabGroupDef[] = [
  // ===============================================
  // EASY (1-14)
  // ===============================================
  {
    id: 'animals',
    title: 'Animals & Pets',
    tier: 'easy',
    sortOrder: 1,
    color: '#2EC4B6',
    icon: 'fi-sr-paw',
    description: 'Common animals and pets',
    keywords: [
      'animal',
      'pet',
      'dog',
      'cat',
      'bird',
      'fish',
      'horse',
      'cow',
      'pig',
      'sheep',
      'duck',
      'chicken',
      'rabbit',
      'mouse',
      'rat',
      'frog',
      'bear',
      'lion',
      'tiger',
      'elephant',
      'monkey',
      'snake',
      'turtle',
      'whale',
      'dolphin',
      'shark',
      'eagle',
      'owl',
      'parrot',
      'butterfly',
      'insect',
      'bee',
      'ant',
      'spider',
      'wing',
      'tail',
      'fur',
      'claw',
      'beak',
      'paw',
      'hoof',
      'zoo',
      'farm',
      'stable',
      'breed',
      'species',
      'mammal',
      'reptile',
      'amphibian',
      'predator',
      'prey',
    ],
    minLevel: 'a1',
    maxLevel: 'b1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'body-parts',
    title: 'Body Parts',
    tier: 'easy',
    sortOrder: 2,
    color: '#FF70A6',
    icon: 'fi-sr-user',
    description: 'Basic body parts vocabulary',
    keywords: [
      'body',
      'head',
      'face',
      'eye',
      'ear',
      'nose',
      'mouth',
      'lip',
      'tooth',
      'tongue',
      'chin',
      'cheek',
      'hair',
      'neck',
      'shoulder',
      'arm',
      'hand',
      'finger',
      'thumb',
      'nail',
      'chest',
      'back',
      'stomach',
      'waist',
      'hip',
      'leg',
      'knee',
      'foot',
      'toe',
      'heel',
      'skin',
      'bone',
      'muscle',
      'heart',
      'brain',
      'lung',
      'blood',
      'joint',
      'elbow',
      'wrist',
      'ankle',
      'throat',
      'spine',
      'rib',
      'palm',
      'fist',
      'forehead',
      'eyebrow',
      'eyelash',
      'nostril',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'colors-shapes',
    title: 'Colors & Shapes',
    tier: 'easy',
    sortOrder: 3,
    color: '#FFBA08',
    icon: 'fi-sr-water',
    description: 'Basic colors and simple shapes',
    keywords: [
      'color',
      'colour',
      'red',
      'blue',
      'green',
      'yellow',
      'black',
      'white',
      'gray',
      'grey',
      'brown',
      'purple',
      'pink',
      'orange',
      'gold',
      'silver',
      'bright',
      'dark',
      'light',
      'pale',
      'vivid',
      'shape',
      'circle',
      'square',
      'triangle',
      'rectangle',
      'round',
      'oval',
      'curve',
      'straight',
      'flat',
      'hollow',
      'solid',
      'pattern',
      'striped',
      'dotted',
      'checkered',
      'shade',
      'tone',
      'rainbow',
      'colorful',
    ],
    minLevel: 'a1',
    maxLevel: 'b1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'family-people',
    title: 'Family & People',
    tier: 'easy',
    sortOrder: 4,
    color: '#E2B237',
    icon: 'fi-sr-users',
    description: 'Family members and people descriptions',
    keywords: [
      'family',
      'mother',
      'father',
      'parent',
      'brother',
      'sister',
      'son',
      'daughter',
      'husband',
      'wife',
      'grandmother',
      'grandfather',
      'grandparent',
      'aunt',
      'uncle',
      'cousin',
      'nephew',
      'niece',
      'baby',
      'child',
      'adult',
      'teenager',
      'toddler',
      'infant',
      'relative',
      'ancestor',
      'descendant',
      'generation',
      'marry',
      'married',
      'wedding',
      'spouse',
      'partner',
      'twin',
      'only child',
      'stepfather',
      'stepmother',
      'half-brother',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'fruits-vegetables',
    title: 'Fruits & Vegetables',
    tier: 'easy',
    sortOrder: 5,
    color: '#2ECC71',
    icon: 'fi-sr-apple-whole',
    description: 'Common fruits and vegetables',
    keywords: [
      'fruit',
      'vegetable',
      'apple',
      'banana',
      'orange',
      'grape',
      'strawberry',
      'blueberry',
      'cherry',
      'peach',
      'pear',
      'plum',
      'melon',
      'watermelon',
      'pineapple',
      'mango',
      'lemon',
      'lime',
      'coconut',
      'avocado',
      'tomato',
      'potato',
      'carrot',
      'onion',
      'garlic',
      'cabbage',
      'lettuce',
      'broccoli',
      'spinach',
      'pepper',
      'cucumber',
      'celery',
      'mushroom',
      'corn',
      'bean',
      'pea',
      'pumpkin',
      'squash',
      'radish',
      'beet',
      'asparagus',
    ],
    minLevel: 'a1',
    maxLevel: 'b1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'meals-dishes',
    title: 'Meals & Dishes',
    tier: 'easy',
    sortOrder: 6,
    color: '#E67E22',
    icon: 'fi-sr-hamburger',
    description: 'Types of meals and prepared dishes',
    keywords: [
      'meal',
      'breakfast',
      'lunch',
      'dinner',
      'supper',
      'snack',
      'dessert',
      'appetizer',
      'main course',
      'side dish',
      'soup',
      'salad',
      'sandwich',
      'pizza',
      'pasta',
      'rice',
      'bread',
      'cake',
      'cookie',
      'pie',
      'burger',
      'fries',
      'chips',
      'sauce',
      'gravy',
      'dressing',
      'soup',
      'stew',
      'curry',
      'toast',
      'cereal',
      'pancake',
      'omelette',
      'noodle',
      'sushi',
      'roast',
      'grill',
      'bake',
      'steam',
      'fry',
      'boil',
      'recipe',
      'ingredient',
      'portion',
      'serving',
      'course',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'drinks-beverages',
    title: 'Drinks & Beverages',
    tier: 'easy',
    sortOrder: 7,
    color: '#3498DB',
    icon: 'fi-sr-glass',
    description: 'Common drinks and beverages',
    keywords: [
      'drink',
      'beverage',
      'water',
      'juice',
      'milk',
      'coffee',
      'tea',
      'soda',
      'cola',
      'lemonade',
      'smoothie',
      'shake',
      'cocktail',
      'beer',
      'wine',
      'whiskey',
      'vodka',
      'rum',
      'gin',
      'champagne',
      'cider',
      'mineral water',
      'sparkling',
      'still',
      'dairy',
      'cream',
      'yogurt drink',
      'sip',
      'gulp',
      'thirsty',
      'refreshing',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'house-home',
    title: 'House & Home',
    tier: 'easy',
    sortOrder: 8,
    color: '#9B59B6',
    icon: 'fi-sr-home',
    description: 'Rooms and things in a home',
    keywords: [
      'house',
      'home',
      'room',
      'kitchen',
      'bedroom',
      'bathroom',
      'living room',
      'dining room',
      'hallway',
      'stairs',
      'basement',
      'attic',
      'garage',
      'garden',
      'yard',
      'balcony',
      'porch',
      'door',
      'window',
      'floor',
      'ceiling',
      'wall',
      'roof',
      'chimney',
      'fence',
      'gate',
      'lock',
      'key',
      'handle',
      'step',
      'entrance',
      'exit',
      'upstairs',
      'downstairs',
      'apartment',
      'flat',
      'cottage',
      'villa',
      'cabin',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'clothing',
    title: 'Clothing',
    tier: 'easy',
    sortOrder: 9,
    color: '#E74C3C',
    icon: 'fi-sr-vest',
    description: 'Basic clothing items',
    keywords: [
      'wear',
      'clothes',
      'clothing',
      'shirt',
      'pants',
      'jeans',
      'dress',
      'skirt',
      'jacket',
      'coat',
      'sweater',
      'hoodie',
      'suit',
      'tie',
      'belt',
      'hat',
      'cap',
      'shoe',
      'boot',
      'sandal',
      'sneaker',
      'sock',
      'underwear',
      'swimsuit',
      'uniform',
      'costume',
      'pajamas',
      'robe',
      'scarf',
      'glove',
      'mitten',
      'sleeve',
      'collar',
      'pocket',
      'button',
      'zipper',
      'fabric',
      'cotton',
      'wool',
      'silk',
      'leather',
      'denim',
      'outfit',
      'garment',
      'wardrobe',
      'fashion',
      'accessory',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'time-calendar',
    title: 'Time & Calendar',
    tier: 'easy',
    sortOrder: 10,
    color: '#1ABC9C',
    icon: 'fi-sr-clock',
    description: 'Days, months, telling time',
    keywords: [
      'time',
      'day',
      'night',
      'morning',
      'afternoon',
      'evening',
      'hour',
      'minute',
      'second',
      'clock',
      'watch',
      'calendar',
      'week',
      'month',
      'year',
      'decade',
      'century',
      'era',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday',
      'weekend',
      'weekday',
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
      'spring',
      'summer',
      'autumn',
      'winter',
      'season',
      'early',
      'late',
      'soon',
      'recent',
      'schedule',
      'deadline',
      'appointment',
      'annual',
      'monthly',
      'weekly',
      'daily',
      'midnight',
      'noon',
      'dawn',
      'dusk',
      'moment',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'weather',
    title: 'Weather',
    tier: 'easy',
    sortOrder: 11,
    color: '#5DADE2',
    icon: 'fi-sr-cloud',
    description: 'Weather conditions and seasons',
    keywords: [
      'weather',
      'rain',
      'rainy',
      'sun',
      'sunny',
      'cloud',
      'cloudy',
      'wind',
      'windy',
      'snow',
      'snowy',
      'storm',
      'stormy',
      'fog',
      'foggy',
      'ice',
      'icy',
      'frost',
      'hail',
      'thunder',
      'lightning',
      'flood',
      'drought',
      'hurricane',
      'tornado',
      'temperature',
      'hot',
      'cold',
      'warm',
      'cool',
      'freeze',
      'humid',
      'humidity',
      'forecast',
      'climate',
      'atmosphere',
      'umbrella',
      'raincoat',
      'thermometer',
      'degree',
      'celsius',
      'breeze',
      'gust',
      'shower',
      'drizzle',
      'downpour',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'numbers-math',
    title: 'Numbers & Math',
    tier: 'easy',
    sortOrder: 12,
    color: '#F39C12',
    icon: 'fi-sr-calculator',
    description: 'Basic numbers and counting',
    keywords: [
      'number',
      'count',
      'zero',
      'one',
      'two',
      'three',
      'four',
      'five',
      'six',
      'seven',
      'eight',
      'nine',
      'ten',
      'hundred',
      'thousand',
      'million',
      'billion',
      'first',
      'second',
      'third',
      'fourth',
      'fifth',
      'last',
      'next',
      'previous',
      'add',
      'subtract',
      'multiply',
      'divide',
      'sum',
      'total',
      'plus',
      'minus',
      'times',
      'equals',
      'calculate',
      'math',
      'dozen',
      'score',
      'pair',
      'double',
      'triple',
      'half',
      'quarter',
      'percentage',
      'fraction',
      'decimal',
      'digit',
      'odd',
      'even',
      'positive',
      'negative',
      'graph',
      'chart',
    ],
    minLevel: 'a1',
    maxLevel: 'b1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'toys-playtime',
    title: 'Toys & Playtime',
    tier: 'easy',
    sortOrder: 13,
    color: '#E91E63',
    icon: 'fi-sr-gamepad',
    description: 'Common toys and playground items',
    keywords: [
      'toy',
      'play',
      'doll',
      'ball',
      'kite',
      'puzzle',
      'block',
      'lego',
      'teddy',
      'bear',
      'robot',
      'action figure',
      'board game',
      'card game',
      'video game',
      'console',
      'remote control',
      'swing',
      'slide',
      'seesaw',
      'jungle gym',
      'playground',
      'sandbox',
      'tricycle',
      'bicycle',
      'scooter',
      'skateboard',
      'jump rope',
      'hula hoop',
      'marble',
      'yo-yo',
      'bubble',
      'stuffed animal',
      'train set',
      'dollhouse',
      'play dough',
      'fun',
      'game',
      'playful',
      'amusement',
    ],
    minLevel: 'a1',
    maxLevel: 'a2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },
  {
    id: 'school-supplies',
    title: 'School Supplies',
    tier: 'easy',
    sortOrder: 14,
    color: '#00BCD4',
    icon: 'fi-sr-backpack',
    description: 'Basic classroom objects',
    keywords: [
      'pencil',
      'pen',
      'eraser',
      'ruler',
      'sharpener',
      'crayon',
      'marker',
      'chalk',
      'board',
      'desk',
      'chair',
      'table',
      'book',
      'notebook',
      'folder',
      'binder',
      'paper',
      'sheet',
      'scissors',
      'glue',
      'tape',
      'stapler',
      'clip',
      'pin',
      'bag',
      'backpack',
      'briefcase',
      'lunchbox',
      'water bottle',
      'calculator',
      'dictionary',
      'textbook',
      'workbook',
      'classroom',
      'library',
      'laboratory',
      'gym',
      'cafeteria',
      'locker',
      'schedule',
      'homework',
      'assignment',
      'grade',
    ],
    minLevel: 'a1',
    maxLevel: 'a2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 4,
  },

  // ===============================================
  // EASY-MEDIUM (15-28)
  // ===============================================
  {
    id: 'nature-outdoors',
    title: 'Nature & Outdoors',
    tier: 'easy-medium',
    sortOrder: 1,
    color: '#27AE60',
    icon: 'fi-sr-tree',
    description: 'Plants, landscapes, and outdoor elements',
    keywords: [
      'tree',
      'plant',
      'flower',
      'grass',
      'leaf',
      'branch',
      'root',
      'seed',
      'garden',
      'forest',
      'jungle',
      'wood',
      'field',
      'mountain',
      'hill',
      'valley',
      'river',
      'lake',
      'ocean',
      'sea',
      'beach',
      'shore',
      'coast',
      'island',
      'desert',
      'cave',
      'waterfall',
      'stream',
      'pond',
      'swamp',
      'cliff',
      'peak',
      'landscape',
      'scenery',
      'nature',
      'wild',
      'outdoor',
      'hike',
      'trail',
      'camp',
      'picnic',
      'barbecue',
      'outdoors',
      'bloom',
      'blossom',
      'petal',
      'pollen',
      'nectar',
      'vine',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'emotions-feelings',
    title: 'Emotions & Feelings',
    tier: 'easy-medium',
    sortOrder: 2,
    color: '#E84393',
    icon: 'fi-sr-smile',
    description: 'Describing how you feel',
    keywords: [
      'happy',
      'sad',
      'angry',
      'scared',
      'excited',
      'nervous',
      'calm',
      'proud',
      'lonely',
      'jealous',
      'embarrassed',
      'confused',
      'surprised',
      'disappointed',
      'grateful',
      'worried',
      'anxious',
      'depressed',
      'frustrated',
      'bored',
      'tired',
      'energetic',
      'relaxed',
      'stressed',
      'hopeful',
      'emotion',
      'feeling',
      'mood',
      'affection',
      'passion',
      'joy',
      'sorrow',
      'anger',
      'fear',
      'love',
      'hate',
      'sympathy',
      'empathy',
      'compassion',
      'tenderness',
      'delight',
      'grief',
      'rage',
      'terror',
      'content',
    ],
    minLevel: 'a1',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'travel-transport',
    title: 'Travel & Transport',
    tier: 'easy-medium',
    sortOrder: 3,
    color: '#0984E3',
    icon: 'fi-sr-plane',
    description: 'Modes of transport and travel vocabulary',
    keywords: [
      'travel',
      'trip',
      'journey',
      'tour',
      'vacation',
      'holiday',
      'visit',
      'sightseeing',
      'tourist',
      'destination',
      'car',
      'bus',
      'train',
      'plane',
      'boat',
      'ship',
      'bike',
      'taxi',
      'subway',
      'tram',
      'ferry',
      'helicopter',
      'airport',
      'station',
      'platform',
      'terminal',
      'gate',
      'ticket',
      'passport',
      'visa',
      'luggage',
      'suitcase',
      'hotel',
      'hostel',
      'resort',
      'inn',
      'cabin',
      'map',
      'guide',
      'route',
      'direction',
      'navigation',
      'abroad',
      'overseas',
      'depart',
      'arrive',
      'board',
      'flight',
      'voyage',
      'cruise',
      'expedition',
      'commute',
    ],
    minLevel: 'a1',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'sports-fitness',
    title: 'Sports & Fitness',
    tier: 'easy-medium',
    sortOrder: 4,
    color: '#00B894',
    icon: 'fi-sr-trophy',
    description: 'Sports, exercises, and fitness activities',
    keywords: [
      'sport',
      'game',
      'play',
      'team',
      'player',
      'coach',
      'train',
      'exercise',
      'fitness',
      'workout',
      'gym',
      'run',
      'swim',
      'football',
      'soccer',
      'basketball',
      'tennis',
      'baseball',
      'golf',
      'volleyball',
      'rugby',
      'hockey',
      'cricket',
      'ski',
      'skate',
      'surf',
      'dive',
      'climb',
      'cycle',
      'race',
      'match',
      'tournament',
      'championship',
      'league',
      'score',
      'goal',
      'point',
      'win',
      'lose',
      'draw',
      'tie',
      'medal',
      'trophy',
      'champion',
      'athlete',
      'referee',
      'stadium',
      'court',
      'field',
      'track',
      'pool',
      'rink',
      'yoga',
      'pilates',
      'aerobics',
      'stretch',
      'jog',
    ],
    minLevel: 'a1',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'school-education',
    title: 'School & Education',
    tier: 'easy-medium',
    sortOrder: 5,
    color: '#6C5CE7',
    icon: 'fi-sr-graduation-cap',
    description: 'Subjects, classrooms, and learning',
    keywords: [
      'school',
      'college',
      'university',
      'class',
      'lesson',
      'course',
      'subject',
      'science',
      'history',
      'math',
      'english',
      'art',
      'music',
      'geography',
      'biology',
      'chemistry',
      'physics',
      'study',
      'learn',
      'teach',
      'educate',
      'train',
      'lecture',
      'professor',
      'teacher',
      'student',
      'pupil',
      'graduate',
      'degree',
      'diploma',
      'certificate',
      'exam',
      'test',
      'quiz',
      'homework',
      'assignment',
      'project',
      'essay',
      'report',
      'grade',
      'score',
      'mark',
      'pass',
      'fail',
      'semester',
      'campus',
      'dormitory',
      'scholarship',
      'tuition',
      'kindergarten',
      'primary',
      'secondary',
      'academic',
    ],
    minLevel: 'a1',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'jobs-occupations',
    title: 'Jobs & Occupations',
    tier: 'easy-medium',
    sortOrder: 6,
    color: '#FD79A8',
    icon: 'fi-sr-briefcase',
    description: 'Different jobs and professions',
    keywords: [
      'job',
      'work',
      'profession',
      'career',
      'occupation',
      'doctor',
      'nurse',
      'teacher',
      'engineer',
      'lawyer',
      'accountant',
      'architect',
      'scientist',
      'artist',
      'writer',
      'musician',
      'actor',
      'pilot',
      'police',
      'firefighter',
      'soldier',
      'farmer',
      'chef',
      'baker',
      'butcher',
      'clerk',
      'manager',
      'director',
      'boss',
      'employee',
      'colleague',
      'assistant',
      'secretary',
      'receptionist',
      'cashier',
      'waiter',
      'waitress',
      'bartender',
      'mechanic',
      'plumber',
      'electrician',
      'carpenter',
      'painter',
      'driver',
      'guard',
      'journalist',
      'photographer',
      'designer',
      'programmer',
      'salary',
      'wage',
      'income',
      'employ',
      'hire',
      'fire',
    ],
    minLevel: 'a1',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'city-places',
    title: 'City & Places',
    tier: 'easy-medium',
    sortOrder: 7,
    color: '#E17055',
    icon: 'fi-sr-hammering',
    description: 'Places in town and city landmarks',
    keywords: [
      'city',
      'town',
      'village',
      'capital',
      'downtown',
      'suburb',
      'neighborhood',
      'block',
      'street',
      'road',
      'avenue',
      'lane',
      'square',
      'market',
      'mall',
      'shop',
      'store',
      'restaurant',
      'cafe',
      'bank',
      'post office',
      'library',
      'museum',
      'theater',
      'cinema',
      'park',
      'church',
      'temple',
      'mosque',
      'hospital',
      'pharmacy',
      'school',
      'station',
      'airport',
      'bridge',
      'tunnel',
      'highway',
      'crosswalk',
      'traffic',
      'landmark',
      'monument',
      'fountain',
      'statue',
      'tower',
      'skyscraper',
      'apartment',
      'office',
      'factory',
      'warehouse',
    ],
    minLevel: 'a1',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'money-shopping',
    title: 'Money & Shopping',
    tier: 'easy-medium',
    sortOrder: 8,
    color: '#FDCB6E',
    icon: 'fi-sr-wallet',
    description: 'Buying, selling, prices, and currency',
    keywords: [
      'money',
      'cash',
      'coin',
      'bill',
      'change',
      'currency',
      'dollar',
      'euro',
      'pound',
      'yen',
      'price',
      'cost',
      'fee',
      'tax',
      'discount',
      'sale',
      'bargain',
      'receipt',
      'refund',
      'pay',
      'buy',
      'purchase',
      'sell',
      'spend',
      'save',
      'earn',
      'afford',
      'cheap',
      'expensive',
      'reasonable',
      'costly',
      'shop',
      'store',
      'market',
      'mall',
      'supermarket',
      'boutique',
      'customer',
      'cashier',
      'checkout',
      'cart',
      'basket',
      'credit',
      'debit',
      'loan',
      'mortgage',
      'interest',
      'debt',
      'budget',
      'account',
      'balance',
      'transfer',
      'withdraw',
    ],
    minLevel: 'a1',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'music-sound',
    title: 'Music & Sound',
    tier: 'easy-medium',
    sortOrder: 9,
    color: '#A29BFE',
    icon: 'fi-sr-music',
    description: 'Musical instruments and sound-related words',
    keywords: [
      'music',
      'song',
      'melody',
      'rhythm',
      'beat',
      'tune',
      'note',
      'guitar',
      'piano',
      'drum',
      'violin',
      'flute',
      'trumpet',
      'saxophone',
      'cello',
      'harp',
      'organ',
      'accordion',
      'singer',
      'musician',
      'band',
      'orchestra',
      'choir',
      'concert',
      'performance',
      'stage',
      'audience',
      'applause',
      'album',
      'single',
      'track',
      'record',
      'playlist',
      'lyrics',
      'verse',
      'chorus',
      'bridge',
      'solo',
      'duet',
      'loud',
      'soft',
      'volume',
      'pitch',
      'tone',
      'sound',
      'noise',
      'echo',
      'vibrate',
      'resonate',
      'acoustic',
      'instrument',
      'composition',
      'improvisation',
    ],
    minLevel: 'a1',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'cooking-kitchen',
    title: 'Cooking & Kitchen',
    tier: 'easy-medium',
    sortOrder: 10,
    color: '#D63031',
    icon: 'fi-sr-utensils',
    description: 'Kitchen tools and cooking actions',
    keywords: [
      'cook',
      'cooking',
      'kitchen',
      'chef',
      'bake',
      'roast',
      'fry',
      'steam',
      'boil',
      'grill',
      'stir',
      'mix',
      'chop',
      'slice',
      'dice',
      'peel',
      'grate',
      'knead',
      'whisk',
      'pot',
      'pan',
      'oven',
      'stove',
      'microwave',
      'blender',
      'knife',
      'spoon',
      'fork',
      'ladle',
      'spatula',
      'strainer',
      'cutting board',
      'bowl',
      'plate',
      'cup',
      'mug',
      'glass',
      'measuring',
      'recipe',
      'ingredient',
      'seasoning',
      'spice',
      'taste',
      'flavor',
      'season',
      'marinate',
      'simmer',
      'appliance',
      'utensil',
      'counter',
      'cabinet',
      'drawer',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'celebrations-holidays',
    title: 'Celebrations & Holidays',
    tier: 'easy-medium',
    sortOrder: 11,
    color: '#FF7675',
    icon: 'fi-sr-gift',
    description: 'Festivals, parties, and special occasions',
    keywords: [
      'celebrate',
      'celebration',
      'party',
      'festival',
      'holiday',
      'Christmas',
      'New Year',
      'Easter',
      'Halloween',
      'Thanksgiving',
      'birthday',
      'anniversary',
      'wedding',
      'graduation',
      'ceremony',
      'ritual',
      'tradition',
      'custom',
      'parade',
      'firework',
      'decoration',
      'balloon',
      'confetti',
      'streamer',
      'gift',
      'present',
      'card',
      'invitation',
      'guest',
      'feast',
      'banquet',
      'reception',
      'toast',
      'speech',
      'dance',
      'music',
      'festive',
      'joyful',
      'merry',
      'vacation',
      'break',
      'festivities',
      'carnival',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'furniture-appliances',
    title: 'Furniture & Appliances',
    tier: 'easy-medium',
    sortOrder: 12,
    color: '#636E72',
    icon: 'fi-sr-bulb',
    description: 'Household furniture and appliances',
    keywords: [
      'furniture',
      'table',
      'chair',
      'desk',
      'bed',
      'sofa',
      'couch',
      'cabinet',
      'shelf',
      'drawer',
      'wardrobe',
      'closet',
      'mirror',
      'lamp',
      'rug',
      'curtain',
      'pillow',
      'blanket',
      'mattress',
      'cushion',
      'stool',
      'bench',
      'shelf',
      'refrigerator',
      'fridge',
      'freezer',
      'dishwasher',
      'washing machine',
      'dryer',
      'vacuum',
      'iron',
      'toaster',
      'kettle',
      'coffee maker',
      'heater',
      'air conditioner',
      'fan',
      'radio',
      'television',
      'lamp',
      'light bulb',
      'appliance',
      'electronic',
      'plug',
      'socket',
      'cord',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'hobbies-interests',
    title: 'Hobbies & Interests',
    tier: 'easy-medium',
    sortOrder: 13,
    color: '#00CEC9',
    icon: 'fi-sr-camera',
    description: 'Free time activities and personal interests',
    keywords: [
      'hobby',
      'interest',
      'pastime',
      'leisure',
      'free time',
      'collect',
      'stamp',
      'coin',
      'model',
      'craft',
      'knit',
      'sew',
      'draw',
      'paint',
      'photography',
      'garden',
      'fish',
      'camp',
      'hike',
      'birdwatch',
      'astronomy',
      'cook',
      'bake',
      'read',
      'write',
      'blog',
      'journal',
      'game',
      'puzzle',
      'crossword',
      'chess',
      'cards',
      'dance',
      'sing',
      'play',
      'instrument',
      'volunteer',
      'travel',
      'explore',
      'learn',
      'DIY',
      'woodworking',
      'pottery',
      'sculpture',
      'origami',
      'calligraphy',
      'relax',
      'unwind',
      'recreation',
      'entertainment',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },
  {
    id: 'describing-people',
    title: 'Describing People',
    tier: 'easy-medium',
    sortOrder: 14,
    color: '#74B9FF',
    icon: 'fi-sr-user',
    description: 'Basic adjectives for appearance and character',
    keywords: [
      'tall',
      'short',
      'young',
      'old',
      'beautiful',
      'handsome',
      'pretty',
      'ugly',
      'thin',
      'slim',
      'fat',
      'strong',
      'weak',
      'kind',
      'mean',
      'friendly',
      'shy',
      'outgoing',
      'honest',
      'lazy',
      'hardworking',
      'smart',
      'stupid',
      'funny',
      'serious',
      'polite',
      'rude',
      'generous',
      'selfish',
      'brave',
      'cowardly',
      'confident',
      'nervous',
      'patient',
      'impatient',
      'careful',
      'careless',
      'organized',
      'messy',
      'creative',
      'curious',
      'appearance',
      'character',
      'personality',
      'trait',
      'blond',
      'brunette',
      'curly',
      'straight',
      'beard',
      'moustache',
      'freckle',
      'wrinkle',
      'dimple',
      'scar',
      'tattoo',
    ],
    minLevel: 'a1',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 6,
  },

  // ===============================================
  // MEDIUM (29-51)
  // ===============================================
  {
    id: 'communication-media',
    title: 'Communication & Media',
    tier: 'medium',
    sortOrder: 1,
    color: '#0984E3',
    icon: 'fi-sr-comment',
    description: 'Talking, writing, news, and social interaction',
    keywords: [
      'communication',
      'communicate',
      'message',
      'text',
      'chat',
      'talk',
      'speak',
      'conversation',
      'discuss',
      'discussion',
      'interview',
      'debate',
      'speech',
      'presentation',
      'news',
      'media',
      'press',
      'journalist',
      'article',
      'report',
      'broadcast',
      'announce',
      'announcement',
      'social media',
      'post',
      'share',
      'comment',
      'like',
      'follow',
      'follower',
      'trend',
      'viral',
      'hashtag',
      'podcast',
      'blog',
      'vlog',
      'stream',
      'influencer',
      'audience',
      'viewer',
      'listener',
      'subscriber',
      'headline',
      'breaking news',
      'coverage',
      'correspondent',
      'editorial',
      'opinion',
      'column',
      'feature',
      'interview',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'technology-devices',
    title: 'Technology & Devices',
    tier: 'medium',
    sortOrder: 2,
    color: '#2D3436',
    icon: 'fi-sr-laptop',
    description: 'Computers, phones, and digital devices',
    keywords: [
      'computer',
      'laptop',
      'desktop',
      'tablet',
      'phone',
      'smartphone',
      'device',
      'gadget',
      'screen',
      'display',
      'keyboard',
      'mouse',
      'monitor',
      'printer',
      'scanner',
      'speaker',
      'headphone',
      'microphone',
      'webcam',
      'software',
      'hardware',
      'app',
      'application',
      'program',
      'update',
      'install',
      'download',
      'upload',
      'sync',
      'digital',
      'electronic',
      'wireless',
      'bluetooth',
      'wifi',
      'battery',
      'charger',
      'cable',
      'port',
      'USB',
      'HDMI',
      'memory',
      'storage',
      'disk',
      'drive',
      'processor',
      'operating system',
      'interface',
      'notification',
      'tech',
      'technology',
      'innovation',
      'invention',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'entertainment-leisure',
    title: 'Entertainment & Leisure',
    tier: 'medium',
    sortOrder: 3,
    color: '#E17055',
    icon: 'fi-sr-ticket',
    description: 'Movies, games, and fun activities',
    keywords: [
      'entertainment',
      'fun',
      'enjoy',
      'enjoyment',
      'leisure',
      'movie',
      'film',
      'cinema',
      'theater',
      'show',
      'performance',
      'concert',
      'festival',
      'circus',
      'magic',
      'comedy',
      'drama',
      'musical',
      'opera',
      'ballet',
      'play',
      'ticket',
      'seat',
      'row',
      'balcony',
      'stage',
      'curtain',
      'audience',
      'applause',
      'encore',
      'standing ovation',
      'game',
      'gaming',
      'console',
      'arcade',
      'casino',
      'lottery',
      'roller coaster',
      'amusement park',
      'water park',
      'zoo',
      'nightclub',
      'bar',
      'pub',
      'karaoke',
      'disco',
      'relax',
      'unwind',
      'recreation',
      'pastime',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'art-creativity',
    title: 'Art & Creativity',
    tier: 'medium',
    sortOrder: 4,
    color: '#E84393',
    icon: 'fi-sr-palette',
    description: 'Drawing, painting, and creative expression',
    keywords: [
      'art',
      'artist',
      'creative',
      'creativity',
      'paint',
      'draw',
      'sketch',
      'canvas',
      'brush',
      'palette',
      'easel',
      'paintbrush',
      'watercolor',
      'oil',
      'acrylic',
      'pastel',
      'charcoal',
      'sculpture',
      'sculpt',
      'clay',
      'pottery',
      'ceramic',
      'gallery',
      'exhibition',
      'museum',
      'masterpiece',
      'portrait',
      'landscape',
      'abstract',
      'still life',
      'illustrate',
      'illustration',
      'cartoon',
      'comic',
      'manga',
      'design',
      'graphic',
      'typography',
      'logo',
      'poster',
      'craft',
      'handmade',
      'DIY',
      'origami',
      'collage',
      'mural',
      'fresco',
      'graffiti',
      'install',
      'artwork',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'health-body',
    title: 'Health & Body',
    tier: 'medium',
    sortOrder: 5,
    color: '#00B894',
    icon: 'fi-sr-heart',
    description: 'Health, illness, exercise, and the human body',
    keywords: [
      'health',
      'healthy',
      'illness',
      'disease',
      'sick',
      'pain',
      'injury',
      'wound',
      'hurt',
      'ache',
      'fever',
      'cough',
      'cold',
      'flu',
      'infection',
      'symptom',
      'diagnosis',
      'medicine',
      'medication',
      'pill',
      'tablet',
      'injection',
      'prescription',
      'treatment',
      'therapy',
      'surgery',
      'doctor',
      'nurse',
      'patient',
      'hospital',
      'clinic',
      'ambulance',
      'emergency',
      'pharmacy',
      'dentist',
      'vitamin',
      'supplement',
      'diet',
      'nutrition',
      'wellness',
      'exercise',
      'fitness',
      'workout',
      'muscle',
      'stretch',
      'massage',
      'acupuncture',
      'chiropractor',
      'remedy',
      'immune',
      'chronic',
      'acute',
      'prevent',
      'vaccine',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'daily-life-routines',
    title: 'Daily Life & Routines',
    tier: 'medium',
    sortOrder: 6,
    color: '#FDCB6E',
    icon: 'fi-sr-calendar',
    description: 'Everyday habits and daily activities',
    keywords: [
      'daily',
      'routine',
      'habit',
      'everyday',
      'regular',
      'morning',
      'evening',
      'bedtime',
      'wake up',
      'get up',
      'brush',
      'shower',
      'bathe',
      'dress',
      'undress',
      'breakfast',
      'lunch',
      'dinner',
      'snack',
      'meal',
      'commute',
      'work',
      'school',
      'arrive',
      'leave',
      'return',
      'cook',
      'clean',
      'tidy',
      'organize',
      'laundry',
      'dishes',
      'shopping',
      'errand',
      'chore',
      'task',
      'duty',
      'sleep',
      'nap',
      'rest',
      'relax',
      'unwind',
      'weekday',
      'weekend',
      'schedule',
      'plan',
      'arrange',
      'usually',
      'often',
      'sometimes',
      'rarely',
      'never',
    ],
    minLevel: 'a2',
    maxLevel: 'b2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'actions-movement',
    title: 'Actions & Movement',
    tier: 'medium',
    sortOrder: 7,
    color: '#6C5CE7',
    icon: 'fi-sr-running',
    description: 'Verbs for movement and physical actions',
    keywords: [
      'walk',
      'run',
      'jump',
      'climb',
      'crawl',
      'slide',
      'slip',
      'fall',
      'rise',
      'lift',
      'lower',
      'bend',
      'stretch',
      'twist',
      'turn',
      'spin',
      'roll',
      'push',
      'pull',
      'carry',
      'hold',
      'grab',
      'catch',
      'throw',
      'toss',
      'kick',
      'stomp',
      'wave',
      'point',
      'tap',
      'pat',
      'rub',
      'scratch',
      'squeeze',
      'press',
      'punch',
      'slap',
      'hug',
      'kiss',
      'jump',
      'hop',
      'skip',
      'leap',
      'dive',
      'swim',
      'crouch',
      'squat',
      'kneel',
      'bow',
      'lean',
      'sway',
      'shiver',
      'tremble',
      'shake',
      'nod',
      'shrug',
      'march',
      'parade',
      'stroll',
      'wander',
      'creep',
      'dash',
      'sprint',
      'rush',
      'hurry',
      'pace',
    ],
    minLevel: 'a1',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'geography-places',
    title: 'Geography & Places',
    tier: 'medium',
    sortOrder: 8,
    color: '#00CEC9',
    icon: 'fi-sr-globe',
    description: 'World regions, landmarks, and locations',
    keywords: [
      'country',
      'nation',
      'state',
      'province',
      'region',
      'continent',
      'Africa',
      'Asia',
      'Europe',
      'America',
      'capital',
      'city',
      'town',
      'village',
      'settlement',
      'border',
      'boundary',
      'territory',
      'zone',
      'district',
      'population',
      'inhabitant',
      'native',
      'citizen',
      'climate',
      'tropical',
      'temperate',
      'arctic',
      'desert',
      'latitude',
      'longitude',
      'equator',
      'hemisphere',
      'map',
      'atlas',
      'globe',
      'chart',
      'coordinate',
      'time zone',
      'local',
      'regional',
      'global',
      'international',
      'North',
      'South',
      'East',
      'West',
      'central',
      'coast',
      'inland',
      'urban',
      'rural',
      'remote',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'environment-ecology',
    title: 'Environment & Ecology',
    tier: 'medium',
    sortOrder: 9,
    color: '#27AE60',
    icon: 'fi-sr-leaf',
    description: 'Nature, climate, and environmental issues',
    keywords: [
      'environment',
      'environmental',
      'ecology',
      'ecosystem',
      'pollution',
      'contaminate',
      'waste',
      'trash',
      'litter',
      'recycle',
      'recyclable',
      'compost',
      'biodegradable',
      'conservation',
      'preserve',
      'protect',
      'endangered',
      'species',
      'habitat',
      'wildlife',
      'biodiversity',
      'climate change',
      'global warming',
      'greenhouse',
      'emission',
      'carbon',
      'fossil fuel',
      'renewable',
      'solar',
      'wind',
      'hydro',
      'geothermal',
      'sustainable',
      'deforestation',
      'extinction',
      'toxic',
      'hazardous',
      'organic',
      'natural',
      'green',
      'clean energy',
      'ozone',
      'rainforest',
      'coral',
      'glacier',
      'sea level',
      'activist',
      'campaign',
      'awareness',
      'conservationist',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'big-synonyms',
    title: 'BIG Synonyms',
    tier: 'medium',
    sortOrder: 10,
    color: '#2D3436',
    icon: 'fi-sr-expand',
    description: 'Synonyms for large, enormous, huge, massive',
    synonymOf: ['big', 'large', 'huge'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'personality-traits',
    title: 'Personality & Character',
    tier: 'medium',
    sortOrder: 11,
    color: '#A29BFE',
    icon: 'fi-sr-user',
    description: 'Character traits and personality descriptions',
    keywords: [
      'personality',
      'character',
      'temperament',
      'nature',
      'optimistic',
      'pessimistic',
      'realistic',
      'idealistic',
      'ambitious',
      'determined',
      'motivated',
      'driven',
      'extrovert',
      'introvert',
      'socialble',
      'reserved',
      'independent',
      'self-reliant',
      'dependable',
      'reliable',
      'mature',
      'immature',
      'responsible',
      'irresponsible',
      'adaptable',
      'flexible',
      'stubborn',
      'rigid',
      'modest',
      'humble',
      'arrogant',
      'conceited',
      'vain',
      'sincere',
      'genuine',
      'hypocrite',
      'superficial',
      'spontaneous',
      'impulsive',
      'cautious',
      'reckless',
      'tolerant',
      'open-minded',
      'prejudiced',
      'narrow-minded',
      'charismatic',
      'charming',
      'witty',
      'diplomatic',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'relationships-social',
    title: 'Relationships & Social',
    tier: 'medium',
    sortOrder: 12,
    color: '#FD79A8',
    icon: 'fi-sr-handshake',
    description: 'Friendships, family bonds, social connections',
    keywords: [
      'friend',
      'friendship',
      'buddy',
      'pal',
      'companion',
      'acquaintance',
      'colleague',
      'classmate',
      'roommate',
      'neighbor',
      'community',
      'society',
      'social',
      'relationship',
      'bond',
      'connection',
      'tie',
      'trust',
      'loyalty',
      'respect',
      'admire',
      'appreciate',
      'support',
      'encourage',
      'comfort',
      'help',
      'care',
      'argue',
      'disagree',
      'conflict',
      'quarrel',
      'fight',
      'forgive',
      'apologize',
      'reconcile',
      'make up',
      'date',
      'dating',
      'romance',
      'romantic',
      'couple',
      'divorce',
      'separate',
      'break up',
      'reunion',
      'gossip',
      'rumor',
      'betray',
      'backstab',
      'scheme',
      'networking',
      'mentor',
      'role model',
      'peer',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'success-achievement',
    title: 'Success & Achievement',
    tier: 'medium',
    sortOrder: 13,
    color: '#F39C12',
    icon: 'fi-sr-star',
    description: 'Goals, accomplishments, reaching milestones',
    keywords: [
      'success',
      'successful',
      'achieve',
      'achievement',
      'goal',
      'target',
      'objective',
      'aim',
      'purpose',
      'accomplish',
      'attain',
      'reach',
      'fulfill',
      'realize',
      'win',
      'victory',
      'triumph',
      'champion',
      'first place',
      'progress',
      'advance',
      'improve',
      'develop',
      'grow',
      'milestone',
      'breakthrough',
      'landmark',
      'feat',
      'award',
      'prize',
      'medal',
      'trophy',
      'honor',
      'recognition',
      'praise',
      'commend',
      'celebrate',
      'overcome',
      'conquer',
      'master',
      'excel',
      'surpass',
      'dedication',
      'persistence',
      'determination',
      'effort',
      'aspiration',
      'ambition',
      'dream',
      'vision',
      'drive',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'problems-solutions',
    title: 'Problems & Solutions',
    tier: 'medium',
    sortOrder: 14,
    color: '#E74C3C',
    icon: 'fi-sr-exclamation',
    description: 'Difficulties, obstacles, and ways to solve them',
    keywords: [
      'problem',
      'issue',
      'difficulty',
      'trouble',
      'dilemma',
      'obstacle',
      'barrier',
      'hurdle',
      'challenge',
      'setback',
      'crisis',
      'emergency',
      'disaster',
      'catastrophe',
      'conflict',
      'dispute',
      'controversy',
      'quandary',
      'solve',
      'solution',
      'resolve',
      'fix',
      'repair',
      'handle',
      'manage',
      'deal with',
      'cope',
      'address',
      'improve',
      'better',
      'remedy',
      'correct',
      'rectify',
      'prevent',
      'avoid',
      'overcome',
      'tackle',
      'combat',
      'strategy',
      'approach',
      'method',
      'plan',
      'answer',
      'brainstorm',
      'analyze',
      'evaluate',
      'decide',
      'act',
      'creative',
      'innovative',
      'practical',
      'effective',
      'root cause',
      'workaround',
      'alternative',
      'option',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'memory-thinking',
    title: 'Memory & Thinking',
    tier: 'medium',
    sortOrder: 15,
    color: '#6C5CE7',
    icon: 'fi-sr-brain',
    description: 'Remembering, forgetting, thought processes',
    keywords: [
      'think',
      'thought',
      'thinking',
      'mind',
      'mental',
      'remember',
      'recall',
      'reminisce',
      'forget',
      'slip',
      'remind',
      'reminder',
      'memorize',
      'memory',
      'memorial',
      'concentrate',
      'focus',
      'attention',
      'distract',
      'imagine',
      'imagination',
      'fantasy',
      'dream',
      'vision',
      'consider',
      'ponder',
      'reflect',
      'contemplate',
      'meditate',
      'analyze',
      'analyze',
      'reason',
      'logic',
      'rational',
      'understand',
      'comprehend',
      'grasp',
      'realize',
      'recognize',
      'confuse',
      'confusion',
      'puzzled',
      'baffle',
      'perplex',
      'judge',
      'judgment',
      'evaluate',
      'assess',
      'estimate',
      'decide',
      'decision',
      'choice',
      'option',
      'conclusion',
      'believe',
      'belief',
      'opinion',
      'view',
      'perspective',
      'assume',
      'assumption',
      'presume',
      'suppose',
      'hypothesis',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'opinions-arguments',
    title: 'Opinions & Arguments',
    tier: 'medium',
    sortOrder: 16,
    color: '#E17055',
    icon: 'fi-sr-comment-dots',
    description: 'Expressing views, agreeing, disagreeing, debating',
    keywords: [
      'opinion',
      'view',
      'point of view',
      'perspective',
      'standpoint',
      'agree',
      'disagree',
      'concur',
      'object',
      'oppose',
      'argue',
      'argument',
      'debate',
      'discuss',
      'dispute',
      'convince',
      'persuade',
      'influence',
      'convince',
      'prove',
      'evidence',
      'proof',
      'fact',
      'data',
      'claim',
      'assert',
      'state',
      'declare',
      'allege',
      'support',
      'back up',
      'defend',
      'justify',
      'rationalize',
      'criticize',
      'critique',
      'review',
      'assess',
      'evaluate',
      'compromise',
      'negotiate',
      'bargain',
      'mediate',
      'consensus',
      'agreement',
      'understanding',
      'accord',
      'contradict',
      'challenge',
      'question',
      'doubt',
      'skeptic',
      'biased',
      'objective',
      'subjective',
      'fair',
      'unfair',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'fashion-style',
    title: 'Fashion & Style',
    tier: 'medium',
    sortOrder: 17,
    color: '#E84393',
    icon: 'fi-sr-vest',
    description: 'Clothing, accessories, personal appearance',
    keywords: [
      'fashion',
      'style',
      'trend',
      'vintage',
      'retro',
      'modern',
      'elegant',
      'chic',
      'classic',
      'casual',
      'formal',
      'accessory',
      'jewelry',
      'necklace',
      'bracelet',
      'ring',
      'earring',
      'watch',
      'sunglasses',
      'belt',
      'scarf',
      'handbag',
      'purse',
      'wallet',
      'backpack',
      'tote',
      'makeup',
      'cosmetic',
      'lipstick',
      'foundation',
      'perfume',
      'hairstyle',
      'haircut',
      'trim',
      'dye',
      'highlights',
      'pattern',
      'stripe',
      'plaid',
      'floral',
      'polka dot',
      'designer',
      'brand',
      'label',
      'collection',
      'runway',
      'model',
      'mannequin',
      'tailor',
      'alteration',
      'hem',
      'outfit',
      'ensemble',
      'attire',
      'apparel',
      'garment',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'books-literature',
    title: 'Books & Literature',
    tier: 'medium',
    sortOrder: 18,
    color: '#A29BFE',
    icon: 'fi-sr-book',
    description: 'Reading, genres, stories, written works',
    keywords: [
      'book',
      'novel',
      'story',
      'tale',
      'fiction',
      'nonfiction',
      'author',
      'writer',
      'poet',
      'playwright',
      'editor',
      'chapter',
      'page',
      'paragraph',
      'sentence',
      'passage',
      'genre',
      'mystery',
      'thriller',
      'romance',
      'fantasy',
      'science fiction',
      'horror',
      'biography',
      'memoir',
      'poem',
      'poetry',
      'rhyme',
      'verse',
      'prose',
      'plot',
      'theme',
      'character',
      'setting',
      'climax',
      'read',
      'reading',
      'bibliophile',
      'bookworm',
      'library',
      'bookshelf',
      'bookstore',
      'publisher',
      'manuscript',
      'draft',
      'edit',
      'proofread',
      'publish',
      'bestseller',
      'paperback',
      'hardcover',
      'edition',
      'index',
      'glossary',
      'appendix',
      'preface',
      'epilogue',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'movies-television',
    title: 'Movies & Television',
    tier: 'medium',
    sortOrder: 19,
    color: '#0984E3',
    icon: 'fi-sr-film',
    description: 'Films, shows, screen entertainment',
    keywords: [
      'movie',
      'film',
      'cinema',
      'screen',
      'motion picture',
      'actor',
      'actress',
      'director',
      'producer',
      'screenwriter',
      'character',
      'role',
      'cast',
      'star',
      'supporting',
      'scene',
      'shot',
      'angle',
      'close-up',
      'slow motion',
      'plot',
      'storyline',
      'twist',
      'ending',
      'cliffhanger',
      'genre',
      'action',
      'comedy',
      'drama',
      'horror',
      'romance',
      'documentary',
      'animation',
      'thriller',
      'musical',
      'series',
      'episode',
      'season',
      'pilot',
      'finale',
      'channel',
      'network',
      'streaming',
      'broadcast',
      'premier',
      'review',
      'critic',
      'rating',
      'audience',
      'box office',
      'trailer',
      'teaser',
      'preview',
      'screening',
      'premier',
      'subtitles',
      'dubbing',
      'soundtrack',
      'score',
      'special effect',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'internet-digital',
    title: 'Internet & Digital Life',
    tier: 'medium',
    sortOrder: 20,
    color: '#00CEC9',
    icon: 'fi-sr-wifi',
    description: 'Online activities, websites, digital culture',
    keywords: [
      'internet',
      'online',
      'web',
      'website',
      'site',
      'page',
      'browser',
      'search',
      'engine',
      'link',
      'URL',
      'domain',
      'email',
      'inbox',
      'spam',
      'attachment',
      'forward',
      'social media',
      'network',
      'profile',
      'feed',
      'post',
      'like',
      'share',
      'comment',
      'mention',
      'tag',
      'follow',
      'unfollow',
      'block',
      'report',
      'privacy',
      'password',
      'login',
      'logout',
      'sign up',
      'account',
      'download',
      'upload',
      'stream',
      'buffer',
      'load',
      'app',
      'extension',
      'plugin',
      'add-on',
      'widget',
      'cookie',
      'cache',
      'history',
      'bookmark',
      'tab',
      'cyber',
      'security',
      'virus',
      'malware',
      'firewall',
      'digital',
      'virtual',
      'online',
      'platform',
      'server',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'buildings-architecture',
    title: 'Buildings & Architecture',
    tier: 'medium',
    sortOrder: 21,
    color: '#636E72',
    icon: 'fi-sr-hammering',
    description: 'Structures, construction, architectural features',
    keywords: [
      'building',
      'structure',
      'construction',
      'architecture',
      'architect',
      'engineer',
      'builder',
      'developer',
      'foundation',
      'frame',
      'beam',
      'column',
      'pillar',
      'floor',
      'story',
      'level',
      'basement',
      'attic',
      'wall',
      'brick',
      'stone',
      'concrete',
      'steel',
      'glass',
      'roof',
      'dome',
      'tower',
      'spire',
      'chimney',
      'gutter',
      'window',
      'door',
      'arch',
      'entrance',
      'exit',
      'corridor',
      'staircase',
      'elevator',
      'escalator',
      'ramp',
      'hall',
      'facade',
      'exterior',
      'interior',
      'lobby',
      'foyer',
      'renovate',
      'restore',
      'remodel',
      'renew',
      'modernize',
      'design',
      'blueprint',
      'plan',
      'sketch',
      'model',
      'residential',
      'commercial',
      'industrial',
      'mixed-use',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'work-business',
    title: 'Work & Business',
    tier: 'medium',
    sortOrder: 22,
    color: '#2D3436',
    icon: 'fi-sr-briefcase',
    description: 'Professional life, offices, workplace activities',
    keywords: [
      'work',
      'workplace',
      'office',
      'desk',
      'cubicle',
      'meeting',
      'colleague',
      'coworker',
      'boss',
      'manager',
      'supervisor',
      'employee',
      'employer',
      'staff',
      'team',
      'department',
      'project',
      'task',
      'assignment',
      'deadline',
      'goal',
      'meeting',
      'agenda',
      'minutes',
      'presentation',
      'report',
      'email',
      'memo',
      'document',
      'file',
      'folder',
      'schedule',
      'appointment',
      'calendar',
      'plan',
      'organize',
      'promotion',
      'raise',
      'bonus',
      'benefit',
      'vacation',
      'resign',
      'quit',
      'fire',
      'layoff',
      'retire',
      'hire',
      'interview',
      'resume',
      'application',
      'candidate',
      'training',
      'workshop',
      'conference',
      'seminar',
      'productivity',
      'efficiency',
      'performance',
      'evaluate',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },
  {
    id: 'materials-textures',
    title: 'Materials & Textures',
    tier: 'medium',
    sortOrder: 23,
    color: '#B2BEC3',
    icon: 'fi-sr-file',
    description: 'Physical materials and surface qualities',
    keywords: [
      'material',
      'substance',
      'matter',
      'element',
      'compound',
      'metal',
      'iron',
      'steel',
      'copper',
      'aluminum',
      'tin',
      'wood',
      'timber',
      'pine',
      'oak',
      'maple',
      'bamboo',
      'plastic',
      'rubber',
      'fiber',
      'fiberglass',
      'carbon',
      'glass',
      'crystal',
      'ceramic',
      'porcelain',
      'clay',
      'fabric',
      'textile',
      'cotton',
      'wool',
      'silk',
      'linen',
      'leather',
      'suede',
      'fur',
      'feather',
      'ivory',
      'stone',
      'rock',
      'marble',
      'granite',
      'slate',
      'limestone',
      'paper',
      'cardboard',
      'carton',
      'foam',
      'sponge',
      'smooth',
      'rough',
      'soft',
      'hard',
      'bumpy',
      'slippery',
      'sticky',
      'greasy',
      'oily',
      'wet',
      'dry',
      'damp',
      'texture',
      'grain',
      'weave',
      'finish',
      'coat',
    ],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 8,
  },

  // ===============================================
  // MEDIUM-HARD (52-68)
  // ===============================================
  {
    id: 'good-synonyms',
    title: 'GOOD Synonyms',
    tier: 'medium-hard',
    sortOrder: 1,
    color: '#27AE60',
    icon: 'fi-sr-thumbs-up',
    description: 'excellent, superb, outstanding, first-rate',
    synonymOf: ['good', 'great', 'excellent'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'bad-synonyms',
    title: 'BAD Synonyms',
    tier: 'medium-hard',
    sortOrder: 2,
    color: '#E74C3C',
    icon: 'fi-sr-thumbs-down',
    description: 'terrible, awful, dreadful, lousy',
    synonymOf: ['bad', 'poor', 'terrible'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'beautiful-synonyms',
    title: 'BEAUTIFUL Synonyms',
    tier: 'medium-hard',
    sortOrder: 3,
    color: '#E84393',
    icon: 'fi-sr-heart',
    description: 'gorgeous, stunning, lovely, breathtaking',
    synonymOf: ['beautiful', 'pretty', 'gorgeous'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'happy-synonyms',
    title: 'HAPPY Synonyms',
    tier: 'medium-hard',
    sortOrder: 4,
    color: '#FDCB6E',
    icon: 'fi-sr-smile',
    description: 'joyful, cheerful, delighted, elated',
    synonymOf: ['happy', 'glad', 'joyful'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'sad-synonyms',
    title: 'SAD Synonyms',
    tier: 'medium-hard',
    sortOrder: 5,
    color: '#5DADE2',
    icon: 'fi-sr-frown',
    description: 'unhappy, gloomy, miserable, sorrowful',
    synonymOf: ['sad', 'unhappy', 'sorrowful'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'angry-synonyms',
    title: 'ANGRY Synonyms',
    tier: 'medium-hard',
    sortOrder: 6,
    color: '#E74C3C',
    icon: 'fi-sr-angry',
    description: 'furious, irritated, enraged, livid',
    synonymOf: ['angry', 'mad', 'furious'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'fast-synonyms',
    title: 'FAST Synonyms',
    tier: 'medium-hard',
    sortOrder: 7,
    color: '#0984E3',
    icon: 'fi-sr-rocket',
    description: 'quick, rapid, swift, speedy',
    synonymOf: ['fast', 'quick', 'rapid'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'important-synonyms',
    title: 'IMPORTANT Synonyms',
    tier: 'medium-hard',
    sortOrder: 8,
    color: '#F39C12',
    icon: 'fi-sr-star',
    description: 'significant, crucial, vital, essential',
    synonymOf: ['important', 'significant', 'crucial'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'difficult-synonyms',
    title: 'DIFFICULT Synonyms',
    tier: 'medium-hard',
    sortOrder: 9,
    color: '#6C5CE7',
    icon: 'fi-sr-puzzle-piece',
    description: 'hard, challenging, tough, arduous',
    synonymOf: ['difficult', 'hard', 'tough'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'smart-synonyms',
    title: 'SMART Synonyms',
    tier: 'medium-hard',
    sortOrder: 10,
    color: '#00CEC9',
    icon: 'fi-sr-bulb',
    description: 'intelligent, clever, brilliant, sharp',
    synonymOf: ['smart', 'intelligent', 'clever'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'funny-synonyms',
    title: 'FUNNY Synonyms',
    tier: 'medium-hard',
    sortOrder: 11,
    color: '#E17055',
    icon: 'fi-sr-laugh',
    description: 'humorous, hilarious, amusing, witty',
    synonymOf: ['funny', 'humorous', 'hilarious'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'strange-synonyms',
    title: 'STRANGE Synonyms',
    tier: 'medium-hard',
    sortOrder: 12,
    color: '#A29BFE',
    icon: 'fi-sr-question',
    description: 'odd, peculiar, bizarre, weird, unusual',
    synonymOf: ['strange', 'weird', 'odd'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'kind-synonyms',
    title: 'KIND Synonyms',
    tier: 'medium-hard',
    sortOrder: 13,
    color: '#00B894',
    icon: 'fi-sr-heart',
    description: 'gentle, compassionate, caring, thoughtful',
    synonymOf: ['kind', 'nice', 'gentle', 'caring'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'brave-synonyms',
    title: 'BRAVE Synonyms',
    tier: 'medium-hard',
    sortOrder: 14,
    color: '#E74C3C',
    icon: 'fi-sr-shield',
    description: 'courageous, fearless, daring, valiant',
    synonymOf: ['brave', 'courageous', 'fearless'],
    minLevel: 'b1',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'famous-synonyms',
    title: 'FAMOUS Synonyms',
    tier: 'medium-hard',
    sortOrder: 15,
    color: '#F39C12',
    icon: 'fi-sr-crown',
    description: 'renowned, celebrated, prominent, notable',
    synonymOf: ['famous', 'well-known', 'renowned'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'quiet-synonyms',
    title: 'QUIET Synonyms',
    tier: 'medium-hard',
    sortOrder: 16,
    color: '#636E72',
    icon: 'fi-sr-moon',
    description: 'silent, still, tranquil, peaceful, calm',
    synonymOf: ['quiet', 'silent', 'calm', 'peaceful'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'honest-synonyms',
    title: 'HONEST Synonyms',
    tier: 'medium-hard',
    sortOrder: 17,
    color: '#27AE60',
    icon: 'fi-sr-check',
    description: 'truthful, sincere, genuine, candid',
    synonymOf: ['honest', 'truthful', 'sincere'],
    minLevel: 'b1',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },

  // ===============================================
  // HARD (69-82)
  // ===============================================
  {
    id: 'strong-synonyms',
    title: 'STRONG Synonyms',
    tier: 'hard',
    sortOrder: 1,
    color: '#2D3436',
    icon: 'fi-sr-gym',
    description: 'powerful, mighty, robust, sturdy, resilient',
    synonymOf: ['strong', 'powerful', 'mighty', 'robust'],
    minLevel: 'b1',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'scared-synonyms',
    title: 'SCARED Synonyms',
    tier: 'hard',
    sortOrder: 2,
    color: '#6C5CE7',
    icon: 'fi-sr-surprise',
    description: 'frightened, terrified, alarmed, anxious',
    synonymOf: ['scared', 'afraid', 'frightened', 'terrified'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'old-synonyms',
    title: 'OLD Synonyms',
    tier: 'hard',
    sortOrder: 3,
    color: '#636E72',
    icon: 'fi-sr-hourglass',
    description: 'ancient, elderly, aged, antique, vintage',
    synonymOf: ['old', 'ancient', 'elderly'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'new-synonyms',
    title: 'NEW Synonyms',
    tier: 'hard',
    sortOrder: 4,
    color: '#00CEC9',
    icon: 'fi-sr-sparkles',
    description: 'modern, recent, fresh, novel, contemporary',
    synonymOf: ['new', 'modern', 'recent', 'fresh'],
    minLevel: 'a2',
    maxLevel: 'c1',
    activityTypes: SYNONYM_ACTIVITIES,
    baseLength: 10,
  },
  {
    id: 'business-commerce',
    title: 'Business & Commerce',
    tier: 'hard',
    sortOrder: 5,
    color: '#0984E3',
    icon: 'fi-sr-chart-pie',
    description: 'Corporate life, trade, commercial activities',
    keywords: [
      'business',
      'commerce',
      'trade',
      'market',
      'industry',
      'company',
      'corporation',
      'enterprise',
      'firm',
      'venture',
      'startup',
      'entrepreneur',
      'investor',
      'shareholder',
      'stock',
      'share',
      'bond',
      'dividend',
      'portfolio',
      'revenue',
      'profit',
      'loss',
      'expense',
      'overhead',
      'budget',
      'forecast',
      'audit',
      'quarterly',
      'annual',
      'merge',
      'acquisition',
      'takeover',
      'IPO',
      'equity',
      'supply chain',
      'logistics',
      'distribution',
      'wholesale',
      'retail',
      'e-commerce',
      'franchise',
      'partnership',
      'CEO',
      'executive',
      'management',
      'board',
      'stakeholder',
      'competitive',
      'monopoly',
      'oligopoly',
      'niche',
      'sector',
      'outsource',
      'offshore',
      'subsidiary',
      'holding',
    ],
    minLevel: 'b1',
    maxLevel: 'c2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 12,
  },
  {
    id: 'law-justice',
    title: 'Law & Justice',
    tier: 'hard',
    sortOrder: 6,
    color: '#E17055',
    icon: 'fi-sr-gavel',
    description: 'Legal systems, courts, and justice',
    keywords: [
      'law',
      'legal',
      'legislation',
      'statute',
      'regulation',
      'court',
      'judge',
      'jury',
      'lawyer',
      'attorney',
      'plaintiff',
      'defendant',
      'accused',
      'witness',
      'testimony',
      'trial',
      'hearing',
      'sentence',
      'verdict',
      'appeal',
      'crime',
      'criminal',
      'offense',
      'felony',
      'misdemeanor',
      'theft',
      'robbery',
      'burglary',
      'assault',
      'fraud',
      'arrest',
      'detain',
      'charge',
      'indict',
      'prosecute',
      'innocent',
      'guilty',
      'evidence',
      'proof',
      'alibi',
      'contract',
      'agreement',
      'treaty',
      'clause',
      'provision',
      'rights',
      'freedom',
      'justice',
      'equality',
      'fairness',
      'constitution',
      'amendment',
      'supreme',
      'federal',
      'enforce',
      'comply',
      'violate',
      'litigation',
      'arbitration',
    ],
    minLevel: 'b1',
    maxLevel: 'c2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 12,
  },
  {
    id: 'science-research',
    title: 'Science & Research',
    tier: 'hard',
    sortOrder: 7,
    color: '#00B894',
    icon: 'fi-sr-test-tube',
    description: 'Scientific study, experiments, discoveries',
    keywords: [
      'science',
      'scientific',
      'research',
      'study',
      'experiment',
      'laboratory',
      'lab',
      'hypothesis',
      'theory',
      'law',
      'data',
      'analysis',
      'observation',
      'measurement',
      'discover',
      'discovery',
      'invention',
      'breakthrough',
      'microscope',
      'telescope',
      'spectrum',
      'particle',
      'atom',
      'molecule',
      'cell',
      'organism',
      'species',
      'gene',
      'DNA',
      'evolution',
      'biology',
      'chemistry',
      'physics',
      'astronomy',
      'geology',
      'botany',
      'zoology',
      'clinical',
      'trial',
      'peer review',
      'publish',
      'journal',
      'sample',
      'specimen',
      'variable',
      'control',
      'result',
      'quantum',
      'nuclear',
      'radiation',
      'laser',
      'robot',
      'innovation',
      'technology',
      'engineering',
      'prototype',
    ],
    minLevel: 'b1',
    maxLevel: 'c2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 12,
  },
  {
    id: 'politics-government',
    title: 'Politics & Government',
    tier: 'hard',
    sortOrder: 8,
    color: '#6C5CE7',
    icon: 'fi-sr-podium',
    description: 'Political systems, governance, public policy',
    keywords: [
      'politics',
      'political',
      'government',
      'governance',
      'democracy',
      'republic',
      'monarchy',
      'dictatorship',
      'election',
      'vote',
      'ballot',
      'campaign',
      'candidate',
      'president',
      'prime minister',
      'senator',
      'congress',
      'parliament',
      'cabinet',
      'minister',
      'official',
      'policy',
      'legislation',
      'reform',
      'regulation',
      'party',
      'conservative',
      'liberal',
      'socialist',
      'diplomacy',
      'foreign policy',
      'treaty',
      'alliance',
      'debate',
      'bipartisan',
      'coalition',
      'opposition',
      'budget',
      'tax',
      'spending',
      'deficit',
      'surplus',
      'bureaucracy',
      'administration',
      'agency',
      'department',
      'citizen',
      'constituent',
      'public',
      'civil service',
      'lobby',
      'interest group',
      'advocacy',
      'activism',
    ],
    minLevel: 'b1',
    maxLevel: 'c2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 12,
  },
  {
    id: 'war-military',
    title: 'War & Military',
    tier: 'hard',
    sortOrder: 9,
    color: '#E74C3C',
    icon: 'fi-sr-shield',
    description: 'Armed conflict, defense, military operations',
    keywords: [
      'war',
      'warfare',
      'battle',
      'fight',
      'conflict',
      'army',
      'navy',
      'air force',
      'marine',
      'soldier',
      'general',
      'colonel',
      'captain',
      'officer',
      'commander',
      'weapon',
      'gun',
      'missile',
      'bomb',
      'tank',
      'aircraft',
      'defense',
      'attack',
      'invade',
      'assault',
      'strike',
      'strategy',
      'tactic',
      'operation',
      'mission',
      'patrol',
      'ally',
      'enemy',
      'troop',
      'force',
      'unit',
      'regiment',
      'casualty',
      'casualties',
      'wound',
      'surrender',
      'ceasefire',
      'peace',
      'truce',
      'treaty',
      'negotiation',
      'disarm',
      'terrorism',
      'insurgency',
      'rebel',
      'guerrilla',
      'veteran',
      'draft',
      'enlist',
      'conscription',
      'reserve',
      'intelligence',
      'spy',
      'espionage',
      'reconnaissance',
    ],
    minLevel: 'b1',
    maxLevel: 'c2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 12,
  },
  {
    id: 'space-astronomy',
    title: 'Space & Astronomy',
    tier: 'hard',
    sortOrder: 10,
    color: '#2D3436',
    icon: 'fi-sr-rocket',
    description: 'Stars, planets, universe, space exploration',
    keywords: [
      'space',
      'universe',
      'cosmos',
      'galaxy',
      'star',
      'planet',
      'earth',
      'moon',
      'sun',
      'solar system',
      'orbit',
      'asteroid',
      'comet',
      'meteor',
      'eclipse',
      'constellation',
      'telescope',
      'observatory',
      'astronomer',
      'astrophysics',
      'rocket',
      'satellite',
      'probe',
      'shuttle',
      'spacecraft',
      'astronaut',
      'cosmonaut',
      'mission',
      'launch',
      'landing',
      'gravity',
      'gravity',
      'black hole',
      'nebula',
      'supernova',
      'radiation',
      'light year',
      'atmosphere',
      'atmosphere',
      'explore',
      'exploration',
      'discover',
      'colonize',
      'NASA',
      'ESA',
      'space station',
      'module',
      'capsule',
      'Martian',
      'lunar',
      'interstellar',
      'extraterrestrial',
      'zero gravity',
      'weightless',
      'vacuum',
      'orbit',
    ],
    minLevel: 'a2',
    maxLevel: 'c2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 12,
  },
  {
    id: 'philosophy-ethics',
    title: 'Philosophy & Ethics',
    tier: 'hard',
    sortOrder: 11,
    color: '#A29BFE',
    icon: 'fi-sr-brain',
    description: 'Abstract ideas, moral principles, belief systems',
    keywords: [
      'philosophy',
      'philosopher',
      'thinker',
      'wisdom',
      'ethics',
      'moral',
      'morality',
      'virtue',
      'value',
      'good',
      'evil',
      'right',
      'wrong',
      'justice',
      'fairness',
      'truth',
      'knowledge',
      'belief',
      'faith',
      'reason',
      'logic',
      'rational',
      'argument',
      'premise',
      'conclusion',
      'consciousness',
      'mind',
      'soul',
      'spirit',
      'existence',
      'free will',
      'destiny',
      'fate',
      'determinism',
      'atheism',
      'theism',
      'religion',
      'spirituality',
      'meaning',
      'purpose',
      'principle',
      'ideal',
      'doctrine',
      'skepticism',
      'empiricism',
      'rationalism',
      'idealism',
      'materialism',
      'nihilism',
      'existentialism',
      'stoic',
      'ontology',
      'epistemology',
      'metaphysics',
      'aesthetic',
    ],
    minLevel: 'b2',
    maxLevel: 'c2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 12,
  },
  {
    id: 'psychology-behavior',
    title: 'Psychology & Behavior',
    tier: 'hard',
    sortOrder: 12,
    color: '#E84393',
    icon: 'fi-sr-brain',
    description: 'Human mind, behavior, mental processes',
    keywords: [
      'psychology',
      'psychologist',
      'psychiatry',
      'therapist',
      'behavior',
      'behavior',
      'mind',
      'mental',
      'cognitive',
      'emotion',
      'motivation',
      'perception',
      'attention',
      'memory',
      'learning',
      'conditioning',
      'reinforcement',
      'personality',
      'trait',
      'temperament',
      'character',
      'conscious',
      'subconscious',
      'unconscious',
      'awareness',
      'intelligence',
      'IQ',
      'genius',
      'gifted',
      'disability',
      'disorder',
      'depression',
      'anxiety',
      'phobia',
      'trauma',
      'therapy',
      'counseling',
      'psychoanalysis',
      'behavioral',
      'development',
      'childhood',
      'adolescent',
      'attachment',
      'social',
      'group',
      'conformity',
      'obedience',
      'bias',
      'self-esteem',
      'confidence',
      'identity',
      'ego',
      'id',
      'neurosis',
      'psychosis',
      'schizophrenia',
      'autism',
      'instinct',
      'drive',
      'impulse',
      'reflex',
      'habit',
    ],
    minLevel: 'b1',
    maxLevel: 'c2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 12,
  },
  {
    id: 'economics-finance',
    title: 'Economics & Finance',
    tier: 'hard',
    sortOrder: 13,
    color: '#F39C12',
    icon: 'fi-sr-stats',
    description: 'Economic systems, markets, financial concepts',
    keywords: [
      'economics',
      'economy',
      'economic',
      'financial',
      'finance',
      'market',
      'capital',
      'asset',
      'liability',
      'equity',
      'inflation',
      'deflation',
      'recession',
      'depression',
      'GDP',
      'growth',
      'stagnation',
      'boom',
      'bust',
      'supply',
      'demand',
      'scarcity',
      'surplus',
      'shortage',
      'interest rate',
      'exchange rate',
      'currency',
      'inflation',
      'bond',
      'stock',
      'futures',
      'option',
      'derivative',
      'bank',
      'central bank',
      'monetary',
      'fiscal',
      'policy',
      'tax',
      'tariff',
      'subsidy',
      'welfare',
      'entitlement',
      'unemployment',
      'employment',
      'labor',
      'wage',
      'salary',
      'investment',
      'speculation',
      'hedge',
      'arbitrage',
      'microeconomics',
      'macroeconomics',
      'monetarism',
      'capitalism',
      'socialism',
      'communism',
      'privatization',
      'globalization',
      'free trade',
      'protectionism',
      'sanction',
    ],
    minLevel: 'b2',
    maxLevel: 'c2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 12,
  },
  {
    id: 'medicine-healthcare',
    title: 'Medicine & Healthcare',
    tier: 'hard',
    sortOrder: 14,
    color: '#E74C3C',
    icon: 'fi-sr-hospital',
    description: 'Advanced medical terms, healthcare systems',
    keywords: [
      'medicine',
      'medical',
      'clinical',
      'diagnosis',
      'prognosis',
      'symptom',
      'syndrome',
      'condition',
      'disorder',
      'disease',
      'treatment',
      'therapy',
      'surgery',
      'procedure',
      'operation',
      'prescription',
      'medication',
      'pharmaceutical',
      'drug',
      'vaccine',
      'immunization',
      'antibiotic',
      'antiviral',
      'chronic',
      'acute',
      'terminal',
      'benign',
      'malignant',
      'cancer',
      'tumor',
      'diabetes',
      'hypertension',
      'asthma',
      'cardiac',
      'neurological',
      'psychiatric',
      'pediatric',
      'emergency',
      'trauma',
      'intensive care',
      'ICU',
      'ward',
      'surgeon',
      'physician',
      'specialist',
      'consultant',
      'anesthesia',
      'transplant',
      'dialysis',
      'chemotherapy',
      'rehabilitation',
      'physical therapy',
      'occupational',
      'healthcare',
      'insurance',
      'Medicare',
      'Medicaid',
      'HMO',
      'epidemic',
      'pandemic',
      'quarantine',
      'contagious',
    ],
    minLevel: 'b1',
    maxLevel: 'c2',
    activityTypes: TOPIC_ACTIVITIES,
    baseLength: 12,
  },
];

// ── Index ──────────────────────────────────────────────────────────────────

const VOCAB_GROUP_MAP = new Map<string, VocabGroupDef>(VOCAB_GROUP_DEFS.map((g) => [g.id, g]));

export function getGroupDef(id: string): VocabGroupDef | undefined {
  return VOCAB_GROUP_MAP.get(id);
}

export function getGroupsByTier(tier: VocabTier): VocabGroupDef[] {
  return VOCAB_GROUP_DEFS.filter((g) => g.tier === tier);
}

function getStageCount(wordCount: number): number {
  if (wordCount < 20) return 1;
  if (wordCount <= 60) return 2;
  return 3;
}

function getLessonCount(stageCount: number): number {
  return stageCount === 1 ? 2 : 3;
}

export function getActivityLengthForTier(tier: VocabTier, accuracy?: number): number {
  const base: Record<VocabTier, number> = {
    easy: 4,
    'easy-medium': 6,
    medium: 8,
    'medium-hard': 10,
    hard: 12,
  };
  const clamp: Record<VocabTier, [number, number]> = {
    easy: [2, 6],
    'easy-medium': [3, 8],
    medium: [4, 10],
    'medium-hard': [6, 12],
    hard: [8, 14],
  };
  let length = base[tier];
  if (accuracy !== undefined) {
    if (accuracy < 0.4) length += 2;
    else if (accuracy > 0.8) length -= 2;
  }
  const [min, max] = clamp[tier];
  return Math.max(min, Math.min(max, length));
}

// ── Word matching ──────────────────────────────────────────────────────────

function wordMatchesGroup(word: WordData, group: VocabGroupDef): boolean {
  if (group.synonymOf && group.synonymOf.length > 0) {
    const lowerSynonyms = word.synonyms.map((s) => s.toLowerCase());
    if (!group.synonymOf.some((s) => lowerSynonyms.includes(s.toLowerCase()))) {
      return false;
    }
  }
  if (group.keywords && group.keywords.length > 0) {
    const searchText = [word.word, word.definition, word.example, ...word.synonyms, word.wordClass]
      .join(' ')
      .toLowerCase();
    if (!group.keywords.some((kw) => searchText.includes(kw.toLowerCase()))) {
      return false;
    }
  }
  if (group.minLevel && word.level !== 'all') {
    if (
      CEFR_LEVEL_ORDER.indexOf(word.level as (typeof CEFR_LEVEL_ORDER)[number]) <
      CEFR_LEVEL_ORDER.indexOf(group.minLevel as (typeof CEFR_LEVEL_ORDER)[number])
    ) {
      return false;
    }
  }
  if (group.maxLevel && word.level !== 'all') {
    if (
      CEFR_LEVEL_ORDER.indexOf(word.level as (typeof CEFR_LEVEL_ORDER)[number]) >
      CEFR_LEVEL_ORDER.indexOf(group.maxLevel as (typeof CEFR_LEVEL_ORDER)[number])
    ) {
      return false;
    }
  }
  return true;
}

// ── Broad match for synonym group fallback ─────────────────────────────────

const SYNONYM_STRICT_THRESHOLD = 10;
const FALLBACK_MIN_WORDS = 5;

function broadWordMatch(word: WordData, group: VocabGroupDef, useLevelFilter = true): boolean {
  const searchText = [word.word, word.definition, word.example, ...word.synonyms, word.wordClass]
    .join(' ')
    .toLowerCase();
  if (
    group.synonymOf &&
    group.synonymOf.length > 0 &&
    !group.synonymOf.some((s) => searchText.includes(s.toLowerCase()))
  ) {
    return false;
  }
  if (useLevelFilter) {
    if (group.minLevel && word.level !== 'all') {
      if (
        CEFR_LEVEL_ORDER.indexOf(word.level as (typeof CEFR_LEVEL_ORDER)[number]) <
        CEFR_LEVEL_ORDER.indexOf(group.minLevel as (typeof CEFR_LEVEL_ORDER)[number])
      )
        return false;
    }
    if (group.maxLevel && word.level !== 'all') {
      if (
        CEFR_LEVEL_ORDER.indexOf(word.level as (typeof CEFR_LEVEL_ORDER)[number]) >
        CEFR_LEVEL_ORDER.indexOf(group.maxLevel as (typeof CEFR_LEVEL_ORDER)[number])
      )
        return false;
    }
  }
  return true;
}

// ── Pre-computed word → group map for O(1) lookup ─────────────────────────

export const wordGroupMap: Record<string, string[]> = {};

for (const word of WORDS) {
  const matchedGroups: string[] = [];
  for (const group of VOCAB_GROUP_DEFS) {
    if (wordMatchesGroup(word, group)) {
      matchedGroups.push(group.id);
    }
  }
  if (matchedGroups.length > 0) {
    wordGroupMap[word.word] = matchedGroups;
  }
}

// ── Public helpers ─────────────────────────────────────────────────────────

export function getWordsForGroup(groupId: string): WordData[] {
  const group = VOCAB_GROUP_MAP.get(groupId);
  if (!group) return [];
  const strict = WORDS.filter((w) => wordMatchesGroup(w, group));
  if (strict.length >= SYNONYM_STRICT_THRESHOLD || !group.synonymOf?.length) {
    return strict;
  }
  const broad = WORDS.filter((w) => broadWordMatch(w, group, true));
  if (broad.length >= FALLBACK_MIN_WORDS) return broad;
  const unfiltered = WORDS.filter((w) => broadWordMatch(w, group, false));
  return unfiltered.length > broad.length ? unfiltered : broad;
}

/**
 * Return contiguous slice of activityTypes for a given stage index within a group.
 * Types cycle if there are more stages than unique types.
 */
export function getActivityTypesForStage(groupId: string, stageIndex: number): ActivityType[] {
  const group = VOCAB_GROUP_MAP.get(groupId);
  if (!group || !group.activityTypes) return [];
  const types = group.activityTypes;
  const stageCount = getStageCount(getWordsForGroup(groupId).length);
  const lessonCount = getLessonCount(stageCount);
  const lessonsNeeded = lessonCount;
  if (types.length === 0) return [];

  const result: ActivityType[] = [];
  for (let i = 0; i < lessonsNeeded; i++) {
    const typeIndex = (stageIndex * lessonsNeeded + i) % types.length;
    result.push(types[typeIndex]);
  }
  return result;
}

export function getGroupsInTier(tier: VocabTier): string[] {
  return VOCAB_GROUP_DEFS.filter((g) => g.tier === tier)
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .map((g) => g.id);
}
