import type { WordData } from "./types";

export const WORDS: WordData[] = [
  {
    word: "cat",
    wordClass: "noun",
    level: "a1",
    ipa: "/kæt/",
    stress: [1],
    syllables: ["cat"],
    phonemes: ["k", "ae", "t"],
    definition: "A small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws.",
    example: "The black cat sat sleepily on the warm rug.",
    wordFamily: ["cats", "catty", "kitten"],
    synonyms: ["feline", "kitty", "puss"],
    collocations: ["pet cat", "domestic cat", "feed the cat"],
    spellingDistractors: ["kat", "cet", "catt"]
  },
  {
    word: "bed",
    wordClass: "noun",
    level: "a1",
    ipa: "/bed/",
    stress: [1],
    syllables: ["bed"],
    phonemes: ["b", "e", "d"],
    definition: "A piece of furniture for sleep or rest, typically a framework with a mattress.",
    example: "She jumped into bed and turned off the lights.",
    wordFamily: ["bedroom", "bedding", "beds"],
    synonyms: ["cot", "couch", "bunk"],
    collocations: ["go to bed", "make the bed", "single bed"],
    spellingDistractors: ["bad", "bet", "bedd"]
  },
  {
    word: "sit",
    wordClass: "verb",
    level: "a1",
    ipa: "/sɪt/",
    stress: [1],
    syllables: ["sit"],
    phonemes: ["s", "i", "t"],
    definition: "Adopt or be in a position in which one's weight is supported by one's buttocks rather than one's feet.",
    example: "Please sit down on the chair.",
    wordFamily: ["sitting", "sat", "seater"],
    synonyms: ["rest", "settle", "perch"],
    collocations: ["sit down", "sit still", "sit comfortably"],
    spellingDistractors: ["sit", "set", "sid"]
  },
  {
    word: "hot",
    wordClass: "adjective",
    level: "a1",
    ipa: "/hɒt/",
    stress: [1],
    syllables: ["hot"],
    phonemes: ["h", "o", "t"],
    definition: "Having a high degree of heat or a high temperature.",
    example: "Be careful, the soup is very hot!",
    wordFamily: ["hotter", "hottest", "heat"],
    synonyms: ["warm", "boiling", "spicy"],
    collocations: ["hot water", "hot weather", "hot day"],
    spellingDistractors: ["hat", "hod", "hott"]
  },
  {
    word: "cup",
    wordClass: "noun",
    level: "a1",
    ipa: "/kʌp/",
    stress: [1],
    syllables: ["cup"],
    phonemes: ["k", "u", "p"],
    definition: "A small bowl-shaped container for drinking from, typically having a handle.",
    example: "He poured a hot cup of tea for his guest.",
    wordFamily: ["cups", "cupcake", "cupboard"],
    synonyms: ["mug", "glass", "chalice"],
    collocations: ["cup of tea", "paper cup", "coffee cup"],
    spellingDistractors: ["cop", "cub", "cupp"]
  },
  {
    word: "car",
    wordClass: "noun",
    level: "a1",
    ipa: "/kɑː(r)/",
    stress: [1],
    syllables: ["car"],
    phonemes: ["k", "ar"],
    definition: "A road vehicle, typically with four wheels, powered by an internal combustion engine.",
    example: "My uncle bought a brand new red car.",
    wordFamily: ["cars", "parking", "garage"],
    synonyms: ["automobile", "vehicle", "ride"],
    collocations: ["drive a car", "park the car", "used car"],
    spellingDistractors: ["cah", "kar", "caar"]
  },
  {
    word: "see",
    wordClass: "verb",
    level: "a1",
    ipa: "/siː/",
    stress: [1],
    syllables: ["see"],
    phonemes: ["s", "ee"],
    definition: "Perceive with the eyes; discern visually.",
    example: "Can you see the birds flying over the lake?",
    wordFamily: ["seeing", "saw", "seen", "sight"],
    synonyms: ["view", "look", "watch"],
    collocations: ["see a doctor", "see you later", "let me see"],
    spellingDistractors: ["sea", "se", "si"]
  },
  {
    word: "moon",
    wordClass: "noun",
    level: "a1",
    ipa: "/muːn/",
    stress: [1],
    syllables: ["moon"],
    phonemes: ["m", "oo", "n"],
    definition: "The natural satellite of the earth, visible by reflected light from the sun.",
    example: "The full moon was shining brightly in the dark sky.",
    wordFamily: ["moonlight", "moons", "moonbeam"],
    synonyms: ["satellite", "luna"],
    collocations: ["full moon", "moon landing", "under the moon"],
    spellingDistractors: ["mun", "moone", "mon"]
  },
  {
    word: "bird",
    wordClass: "noun",
    level: "a2",
    ipa: "/bɜːd/",
    stress: [1],
    syllables: ["bird"],
    phonemes: ["b", "er", "d"],
    definition: "A feathered, winged, egg-laying, vertebrate animal that can fly.",
    example: "A colorful bird is singing outside my bedroom window.",
    wordFamily: ["birds", "birdhouse", "feather"],
    synonyms: ["fowl", "avian", "songbird"],
    collocations: ["early bird", "wild bird", "bird nest"],
    spellingDistractors: ["berd", "birt", "brid"]
  },
  {
    word: "day",
    wordClass: "noun",
    level: "a1",
    ipa: "/deɪ/",
    stress: [1],
    syllables: ["day"],
    phonemes: ["d", "ay"],
    definition: "A period of twenty-four hours, corresponding to the rotation of the earth.",
    example: "It was a beautiful sunny day to go to the beach.",
    wordFamily: ["daily", "days", "daylight"],
    synonyms: ["daytime", "date"],
    collocations: ["have a nice day", "all day long", "next day"],
    spellingDistractors: ["dey", "dae", "dai"]
  },
  {
    word: "fly",
    wordClass: "verb",
    level: "a2",
    ipa: "/flaɪ/",
    stress: [1],
    syllables: ["fly"],
    phonemes: ["f", "l", "ie"],
    definition: "Move through the air under control, using wings or a machine.",
    example: "In summer, eagles fly high above the mountains.",
    wordFamily: ["flying", "flew", "flown", "flight"],
    synonyms: ["soar", "glide", "hover"],
    collocations: ["fly a kite", "fly a plane", "let fly"],
    spellingDistractors: ["flai", "flye", "flei"]
  },
  {
    word: "boy",
    wordClass: "noun",
    level: "a1",
    ipa: "/bɔɪ/",
    stress: [1],
    syllables: ["boy"],
    phonemes: ["b", "oy"],
    definition: "A male child or young man.",
    example: "The young boy was playing soccer in the park.",
    wordFamily: ["boyhood", "boys", "boyfriend"],
    synonyms: ["lad", "youth", "male"],
    collocations: ["young boy", "little boy", "baby boy"],
    spellingDistractors: ["boi", "boye", "booy"]
  },
  {
    word: "now",
    wordClass: "adverb",
    level: "a1",
    ipa: "/naʊ/",
    stress: [1],
    syllables: ["now"],
    phonemes: ["n", "ow"],
    definition: "At the present time or moment.",
    example: "We need to leave now if we want to catch the bus.",
    wordFamily: ["nowadays", "now"],
    synonyms: ["currently", "immediately", "instantly"],
    collocations: ["right now", "now and then", "up to now"],
    spellingDistractors: ["nau", "nou", "nowe"]
  },
  {
    word: "about",
    wordClass: "preposition",
    level: "a1",
    ipa: "/əˈbaʊt/",
    stress: [0, 1],
    syllables: ["a", "bout"],
    phonemes: ["uh", "b", "ow", "t"],
    definition: "On the subject of; concerning.",
    example: "Tell me more about your trip to England.",
    wordFamily: ["abouts"],
    synonyms: ["regarding", "concerning"],
    collocations: ["ask about", "think about", "talk about"],
    spellingDistractors: ["abaut", "aboutt", "aboute"]
  },
  {
    word: "near",
    wordClass: "adjective",
    level: "b1",
    ipa: "/nɪə(r)/",
    stress: [1],
    syllables: ["near"],
    phonemes: ["n", "eer"],
    definition: "At or to a short distance away; close by.",
    example: "My school is situated near the public library.",
    wordFamily: ["nearby", "nearness", "nearly"],
    synonyms: ["close", "adjacent", "local"],
    collocations: ["near future", "near distance", "nowhere near"],
    spellingDistractors: ["neer", "nia", "nere"]
  },
  {
    word: "care",
    wordClass: "noun",
    level: "b1",
    ipa: "/keə(r)/",
    stress: [1],
    syllables: ["care"],
    phonemes: ["k", "air"],
    definition: "The provision of what is necessary for the health, welfare, maintenance, and protection of someone or something.",
    example: "Taking care of a pet is a big responsibility.",
    wordFamily: ["careful", "careless", "caring"],
    synonyms: ["attention", "caution", "concern"],
    collocations: ["take care", "medical care", "care provider"],
    spellingDistractors: ["kair", "caer", "cair"]
  },
  {
    word: "tour",
    wordClass: "noun",
    level: "b1",
    ipa: "/tʊə(r)/",
    stress: [1],
    syllables: ["tour"],
    phonemes: ["t", "oor"],
    definition: "A journey for pleasure in which several places are visited.",
    example: "We went on a guided walking tour of the ancient city.",
    wordFamily: ["tourism", "tourist", "touring"],
    synonyms: ["journey", "trip", "excursion"],
    collocations: ["guided tour", "world tour", "study tour"],
    spellingDistractors: ["tua", "toor", "ture"]
  },
  {
    word: "book",
    wordClass: "noun",
    level: "a1",
    ipa: "/bʊk/",
    stress: [1],
    syllables: ["book"],
    phonemes: ["b", "uh2", "k"],
    definition: "A written or printed work consisting of pages glued or sewn together along one side.",
    example: "I am reading an interesting book about dinosaurs.",
    wordFamily: ["books", "bookcase", "bookstore", "booking"],
    synonyms: ["volume", "novel", "manual"],
    collocations: ["read a book", "write a book", "text book"],
    spellingDistractors: ["buk", "booke", "bouk"]
  },
  {
    word: "ship",
    wordClass: "noun",
    level: "a1",
    ipa: "/ʃɪp/",
    stress: [1],
    syllables: ["ship"],
    phonemes: ["sh", "i", "p"],
    definition: "A large boat for transporting people or goods by sea.",
    example: "A huge cargo ship passed under the bridge.",
    wordFamily: ["shipping", "shipment", "ships"],
    synonyms: ["vessel", "boat", "liner"],
    collocations: ["cruise ship", "cargo ship", "board the ship"],
    spellingDistractors: ["sip", "chip", "shipp"]
  },
  {
    word: "measure",
    wordClass: "verb",
    level: "b2",
    ipa: "/ˈmeʒə(r)/",
    stress: [1, 0],
    syllables: ["mea", "sure"],
    phonemes: ["m", "e", "zh", "uh"],
    definition: "Ascertain the size, amount, or degree of something by comparison with a standard unit.",
    example: "We need to measure the width of this desk.",
    wordFamily: ["measurement", "measurable", "measured"],
    synonyms: ["assess", "evaluate", "gauge"],
    collocations: ["measure success", "measure progress", "tape measure"],
    spellingDistractors: ["masur", "measer", "meazure"]
  },
  {
    word: "chin",
    wordClass: "noun",
    level: "a2",
    ipa: "/tʃɪn/",
    stress: [1],
    syllables: ["chin"],
    phonemes: ["ch", "i", "n"],
    definition: "The protruding part of the face below the mouth, formed by the apex of the lower jaw.",
    example: "He rubbed his chin thoughtfully while looking at the map.",
    wordFamily: ["chins"],
    synonyms: ["jawline", "jaw"],
    collocations: ["double chin", "rub your chin", "chin up"],
    spellingDistractors: ["cin", "shin", "chinn"]
  },
  {
    word: "jump",
    wordClass: "verb",
    level: "a1",
    ipa: "/dʒʌmp/",
    stress: [1],
    syllables: ["jump"],
    phonemes: ["dz", "u", "m", "p"],
    definition: "Push oneself off a surface and into the air by using the muscles in one's legs and feet.",
    example: "The children like to jump on the trampoline.",
    wordFamily: ["jumping", "jumped", "jumper"],
    synonyms: ["leap", "hop", "bound"],
    collocations: ["jump high", "jump over", "jump up"],
    spellingDistractors: ["gump", "cump", "jumpp"]
  },
  {
    word: "sing",
    wordClass: "verb",
    level: "a1",
    ipa: "/sɪŋ/",
    stress: [1],
    syllables: ["sing"],
    phonemes: ["s", "i", "ng"],
    definition: "Make musical sounds with the voice, especially words with a set tune.",
    example: "They gathered around the campfire to sing songs.",
    wordFamily: ["singer", "singing", "sang", "sung"],
    synonyms: ["carol", "chant", "hum"],
    collocations: ["sing a song", "sing along", "choir singing"],
    spellingDistractors: ["sin", "singg", "sink"]
  },
  {
    word: "thin",
    wordClass: "adjective",
    level: "b1",
    ipa: "/θɪn/",
    stress: [1],
    syllables: ["thin"],
    phonemes: ["th", "i", "n"],
    definition: "Having opposite surfaces or sides close together; of little thickness.",
    example: "He wore a thin jacket despite the cold wind.",
    wordFamily: ["thinner", "thinnest", "thinly"],
    synonyms: ["slim", "slender", "skinny"],
    collocations: ["thin line", "thin layer", "thin ice"],
    spellingDistractors: ["tin", "phin", "thinn"]
  },
  {
    word: "this",
    wordClass: "pronoun",
    level: "a1",
    ipa: "/ðɪs/",
    stress: [1],
    syllables: ["this"],
    phonemes: ["dh", "i", "s"],
    definition: "Used to identify a specific person or thing close at hand or being indicated.",
    example: "This is my favorite book in the library.",
    wordFamily: ["these"],
    synonyms: ["here"],
    collocations: ["this one", "this time", "like this"],
    spellingDistractors: ["dis", "tis", "thiss"]
  },
  {
    word: "correct",
    wordClass: "adjective",
    level: "b1",
    ipa: "/kəˈrekt/",
    stress: [0, 1],
    syllables: ["cor", "rect"],
    phonemes: ["k", "uh", "r", "e", "k", "t"],
    definition: "Free from error; in accordance with fact or truth.",
    example: "Make sure all your answers are correct before submitting.",
    wordFamily: ["correctly", "correction", "incorrect"],
    synonyms: ["right", "accurate", "proper"],
    collocations: ["correct answer", "correct procedure", "politically correct"],
    spellingDistractors: ["collect", "corect", "correkt"]
  },
  {
    word: "office",
    wordClass: "noun",
    level: "b1",
    ipa: "/ˈɒfɪs/",
    stress: [1, 0],
    syllables: ["of", "fice"],
    phonemes: ["o", "f", "i", "s"],
    definition: "A room, set of rooms, or building used as a place for commercial, professional, or bureaucratic work.",
    example: "He works at a high-tech software office in downtown.",
    wordFamily: ["officer", "official", "officially"],
    synonyms: ["headquarters", "branch", "bureau"],
    collocations: ["post office", "box office", "office hour"],
    spellingDistractors: ["offis", "ofice", "offise"]
  },
  {
    word: "wash",
    wordClass: "verb",
    level: "a1",
    ipa: "/wɒʃ/",
    stress: [1],
    syllables: ["wash"],
    phonemes: ["w", "o", "sh"],
    definition: "Clean with water and, typically, soap or detergent.",
    example: "Remember to wash your hands before eating dinner.",
    wordFamily: ["washing", "washed", "washer"],
    synonyms: ["clean", "rinse", "scrub"],
    collocations: ["wash hands", "wash dishes", "car wash"],
    spellingDistractors: ["wat", "wosh", "washe"]
  },
  {
    word: "hope",
    wordClass: "verb",
    level: "a2",
    ipa: "/həʊp/",
    stress: [1],
    syllables: ["hope"],
    phonemes: ["h", "oh", "p"],
    definition: "Want something to happen or be the case, and think it is possible.",
    example: "I hope that you will pass the English exam tomorrow.",
    wordFamily: ["hopeful", "hopeless", "hoping"],
    synonyms: ["wish", "aspire", "desire"],
    collocations: ["hope for", "sincere hope", "ray of hope"],
    spellingDistractors: ["hop", "hoap", "hopee"]
  }
];
