import type { WordData } from './types';
import enrichedData from '@/data/words/all-words.json';

const ENRICHED_WORDS: WordData[] = enrichedData as WordData[];

const LEGACY_WORDS: WordData[] = [
  // ─── Original Vocabulary (29 words) ───
  {
    word: 'cat',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/kæt/',
    stress: [1],
    syllables: ['cat'],
    phonemes: ['k', 'ae', 't'],
    definition:
      'A small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws.',
    example: 'The black cat sat sleepily on the warm rug.',
    wordFamily: ['cats', 'catty', 'kitten'],
    synonyms: ['feline', 'kitty', 'puss'],
    collocations: ['pet cat', 'domestic cat', 'feed the cat'],
    antonyms: [],
    spellingDistractors: ['kat', 'cet', 'catt'],
  },
  {
    word: 'bed',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/bed/',
    stress: [1],
    syllables: ['bed'],
    phonemes: ['b', 'e', 'd'],
    definition: 'A piece of furniture for sleep or rest, typically a framework with a mattress.',
    example: 'She jumped into bed and turned off the lights.',
    wordFamily: ['bedroom', 'bedding', 'beds'],
    synonyms: ['cot', 'couch', 'bunk'],
    collocations: ['go to bed', 'make the bed', 'single bed'],
    antonyms: [],
    spellingDistractors: ['bad', 'bet', 'bedd'],
  },
  {
    word: 'sit',
    wordClass: 'verb',
    level: 'a1',
    ipa: '/sɪt/',
    stress: [1],
    syllables: ['sit'],
    phonemes: ['s', 'i', 't'],
    definition:
      "Adopt or be in a position in which one's weight is supported by one's buttocks rather than one's feet.",
    example: 'Please sit down on the chair.',
    wordFamily: ['sitting', 'sat', 'seater'],
    synonyms: ['rest', 'settle', 'perch'],
    collocations: ['sit down', 'sit still', 'sit comfortably'],
    antonyms: [],
    spellingDistractors: ['set', 'sid'],
  },
  {
    word: 'hot',
    wordClass: 'adjective',
    level: 'a1',
    ipa: '/hɒt/',
    stress: [1],
    syllables: ['hot'],
    phonemes: ['h', 'o', 't'],
    definition: 'Having a high degree of heat or a high temperature.',
    example: 'Be careful, the soup is very hot!',
    wordFamily: ['hotter', 'hottest', 'heat'],
    synonyms: ['warm', 'boiling', 'spicy'],
    collocations: ['hot water', 'hot weather', 'hot day'],
    antonyms: [],
    spellingDistractors: ['hat', 'hod', 'hott'],
  },
  {
    word: 'cup',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/kʌp/',
    stress: [1],
    syllables: ['cup'],
    phonemes: ['k', 'u', 'p'],
    definition: 'A small bowl-shaped container for drinking from, typically having a handle.',
    example: 'He poured a hot cup of tea for his guest.',
    wordFamily: ['cups', 'cupcake', 'cupboard'],
    synonyms: ['mug', 'glass', 'chalice'],
    collocations: ['cup of tea', 'paper cup', 'coffee cup'],
    antonyms: [],
    spellingDistractors: ['cop', 'cub', 'cupp'],
  },
  {
    word: 'car',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/kɑː(r)/',
    stress: [1],
    syllables: ['car'],
    phonemes: ['k', 'ar'],
    definition:
      'A road vehicle, typically with four wheels, powered by an internal combustion engine.',
    example: 'My uncle bought a brand new red car.',
    wordFamily: ['cars', 'parking', 'garage'],
    synonyms: ['automobile', 'vehicle', 'ride'],
    collocations: ['drive a car', 'park the car', 'used car'],
    antonyms: [],
    spellingDistractors: ['cah', 'kar', 'caar'],
  },
  {
    word: 'see',
    wordClass: 'verb',
    level: 'a1',
    ipa: '/siː/',
    stress: [1],
    syllables: ['see'],
    phonemes: ['s', 'ee'],
    definition: 'Perceive with the eyes; discern visually.',
    example: 'Can you see the birds flying over the lake?',
    wordFamily: ['seeing', 'saw', 'seen', 'sight'],
    synonyms: ['view', 'look', 'watch'],
    collocations: ['see a doctor', 'see you later', 'let me see'],
    antonyms: [],
    spellingDistractors: ['sea', 'se', 'si'],
  },
  {
    word: 'moon',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/muːn/',
    stress: [1],
    syllables: ['moon'],
    phonemes: ['m', 'oo', 'n'],
    definition: 'The natural satellite of the earth, visible by reflected light from the sun.',
    example: 'The full moon was shining brightly in the dark sky.',
    wordFamily: ['moonlight', 'moons', 'moonbeam'],
    synonyms: ['satellite', 'luna'],
    collocations: ['full moon', 'moon landing', 'under the moon'],
    antonyms: [],
    spellingDistractors: ['mun', 'moone', 'mon'],
  },
  {
    word: 'bird',
    wordClass: 'noun',
    level: 'a2',
    ipa: '/bɜːd/',
    stress: [1],
    syllables: ['bird'],
    phonemes: ['b', 'er', 'd'],
    definition: 'A feathered, winged, egg-laying, vertebrate animal that can fly.',
    example: 'A colorful bird is singing outside my bedroom window.',
    wordFamily: ['birds', 'birdhouse', 'feather'],
    synonyms: ['fowl', 'avian', 'songbird'],
    collocations: ['early bird', 'wild bird', 'bird nest'],
    antonyms: [],
    spellingDistractors: ['berd', 'birt', 'brid'],
  },
  {
    word: 'day',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/deɪ/',
    stress: [1],
    syllables: ['day'],
    phonemes: ['d', 'ay'],
    definition: 'A period of twenty-four hours, corresponding to the rotation of the earth.',
    example: 'It was a beautiful sunny day to go to the beach.',
    wordFamily: ['daily', 'days', 'daylight'],
    synonyms: ['daytime', 'date'],
    collocations: ['have a nice day', 'all day long', 'next day'],
    antonyms: [],
    spellingDistractors: ['dey', 'dae', 'dai'],
  },
  {
    word: 'fly',
    wordClass: 'verb',
    level: 'a2',
    ipa: '/flaɪ/',
    stress: [1],
    syllables: ['fly'],
    phonemes: ['f', 'l', 'ie'],
    definition: 'Move through the air under control, using wings or a machine.',
    example: 'In summer, eagles fly high above the mountains.',
    wordFamily: ['flying', 'flew', 'flown', 'flight'],
    synonyms: ['soar', 'glide', 'hover'],
    collocations: ['fly a kite', 'fly a plane', 'let fly'],
    antonyms: [],
    spellingDistractors: ['flai', 'flye', 'flei'],
  },
  {
    word: 'boy',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/bɔɪ/',
    stress: [1],
    syllables: ['boy'],
    phonemes: ['b', 'oy'],
    definition: 'A male child or young man.',
    example: 'The young boy was playing soccer in the park.',
    wordFamily: ['boyhood', 'boys', 'boyfriend'],
    synonyms: ['lad', 'youth', 'male'],
    collocations: ['young boy', 'little boy', 'baby boy'],
    antonyms: [],
    spellingDistractors: ['boi', 'boye', 'booy'],
  },
  {
    word: 'now',
    wordClass: 'adverb',
    level: 'a1',
    ipa: '/naʊ/',
    stress: [1],
    syllables: ['now'],
    phonemes: ['n', 'ow'],
    definition: 'At the present time or moment.',
    example: 'We need to leave now if we want to catch the bus.',
    wordFamily: ['nowadays', 'now'],
    synonyms: ['currently', 'immediately', 'instantly'],
    collocations: ['right now', 'now and then', 'up to now'],
    antonyms: [],
    spellingDistractors: ['nau', 'nou', 'nowe'],
  },
  {
    word: 'about',
    wordClass: 'preposition',
    level: 'a1',
    ipa: '/əˈbaʊt/',
    stress: [0, 1],
    syllables: ['a', 'bout'],
    phonemes: ['uh', 'b', 'ow', 't'],
    definition: 'On the subject of; concerning.',
    example: 'Tell me more about your trip to England.',
    wordFamily: ['abouts'],
    synonyms: ['regarding', 'concerning'],
    collocations: ['ask about', 'think about', 'talk about'],
    antonyms: [],
    spellingDistractors: ['abaut', 'aboutt', 'aboute'],
  },
  {
    word: 'near',
    wordClass: 'adjective',
    level: 'b1',
    ipa: '/nɪə(r)/',
    stress: [1],
    syllables: ['near'],
    phonemes: ['n', 'eer'],
    definition: 'At or to a short distance away; close by.',
    example: 'My school is situated near the public library.',
    wordFamily: ['nearby', 'nearness', 'nearly'],
    synonyms: ['close', 'adjacent', 'local'],
    collocations: ['near future', 'near distance', 'nowhere near'],
    antonyms: [],
    spellingDistractors: ['neer', 'nia', 'nere'],
  },
  {
    word: 'care',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/keə(r)/',
    stress: [1],
    syllables: ['care'],
    phonemes: ['k', 'air'],
    definition:
      'The provision of what is necessary for the health, welfare, maintenance, and protection of someone or something.',
    example: 'Taking care of a pet is a big responsibility.',
    wordFamily: ['careful', 'careless', 'caring'],
    synonyms: ['attention', 'caution', 'concern'],
    collocations: ['take care', 'medical care', 'care provider'],
    antonyms: [],
    spellingDistractors: ['kair', 'caer', 'cair'],
  },
  {
    word: 'tour',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/tʊə(r)/',
    stress: [1],
    syllables: ['tour'],
    phonemes: ['t', 'oor'],
    definition: 'A journey for pleasure in which several places are visited.',
    example: 'We went on a guided walking tour of the ancient city.',
    wordFamily: ['tourism', 'tourist', 'touring'],
    synonyms: ['journey', 'trip', 'excursion'],
    collocations: ['guided tour', 'world tour', 'study tour'],
    antonyms: [],
    spellingDistractors: ['tua', 'toor', 'ture'],
  },
  {
    word: 'book',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/bʊk/',
    stress: [1],
    syllables: ['book'],
    phonemes: ['b', 'uh2', 'k'],
    definition:
      'A written or printed work consisting of pages glued or sewn together along one side.',
    example: 'I am reading an interesting book about dinosaurs.',
    wordFamily: ['books', 'bookcase', 'bookstore', 'booking'],
    synonyms: ['volume', 'novel', 'manual'],
    collocations: ['read a book', 'write a book', 'text book'],
    antonyms: [],
    spellingDistractors: ['buk', 'booke', 'bouk'],
  },
  {
    word: 'ship',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/ʃɪp/',
    stress: [1],
    syllables: ['ship'],
    phonemes: ['sh', 'i', 'p'],
    definition: 'A large boat for transporting people or goods by sea.',
    example: 'A huge cargo ship passed under the bridge.',
    wordFamily: ['shipping', 'shipment', 'ships'],
    synonyms: ['vessel', 'boat', 'liner'],
    collocations: ['cruise ship', 'cargo ship', 'board the ship'],
    antonyms: [],
    spellingDistractors: ['sip', 'chip', 'shipp'],
  },
  {
    word: 'measure',
    wordClass: 'verb',
    level: 'b2',
    ipa: '/ˈmeʒə(r)/',
    stress: [1, 0],
    syllables: ['mea', 'sure'],
    phonemes: ['m', 'e', 'zh', 'uh'],
    definition:
      'Ascertain the size, amount, or degree of something by comparison with a standard unit.',
    example: 'We need to measure the width of this desk.',
    wordFamily: ['measurement', 'measurable', 'measured'],
    synonyms: ['assess', 'evaluate', 'gauge'],
    collocations: ['measure success', 'measure progress', 'tape measure'],
    antonyms: [],
    spellingDistractors: ['masur', 'measer', 'meazure'],
  },
  {
    word: 'chin',
    wordClass: 'noun',
    level: 'a2',
    ipa: '/tʃɪn/',
    stress: [1],
    syllables: ['chin'],
    phonemes: ['ch', 'i', 'n'],
    definition:
      'The protruding part of the face below the mouth, formed by the apex of the lower jaw.',
    example: 'He rubbed his chin thoughtfully while looking at the map.',
    wordFamily: ['chins'],
    synonyms: ['jawline', 'jaw'],
    collocations: ['double chin', 'rub your chin', 'chin up'],
    antonyms: [],
    spellingDistractors: ['cin', 'shin', 'chinn'],
  },
  {
    word: 'jump',
    wordClass: 'verb',
    level: 'a1',
    ipa: '/dʒʌmp/',
    stress: [1],
    syllables: ['jump'],
    phonemes: ['dz', 'u', 'm', 'p'],
    definition:
      "Push oneself off a surface and into the air by using the muscles in one's legs and feet.",
    example: 'The children like to jump on the trampoline.',
    wordFamily: ['jumping', 'jumped', 'jumper'],
    synonyms: ['leap', 'hop', 'bound'],
    collocations: ['jump high', 'jump over', 'jump up'],
    antonyms: [],
    spellingDistractors: ['gump', 'cump', 'jumpp'],
  },
  {
    word: 'sing',
    wordClass: 'verb',
    level: 'a1',
    ipa: '/sɪŋ/',
    stress: [1],
    syllables: ['sing'],
    phonemes: ['s', 'i', 'ng'],
    definition: 'Make musical sounds with the voice, especially words with a set tune.',
    example: 'They gathered around the campfire to sing songs.',
    wordFamily: ['singer', 'singing', 'sang', 'sung'],
    synonyms: ['carol', 'chant', 'hum'],
    collocations: ['sing a song', 'sing along', 'choir singing'],
    antonyms: [],
    spellingDistractors: ['sin', 'singg', 'sink'],
  },
  {
    word: 'thin',
    wordClass: 'adjective',
    level: 'b1',
    ipa: '/θɪn/',
    stress: [1],
    syllables: ['thin'],
    phonemes: ['th', 'i', 'n'],
    definition: 'Having opposite surfaces or sides close together; of little thickness.',
    example: 'He wore a thin jacket despite the cold wind.',
    wordFamily: ['thinner', 'thinnest', 'thinly'],
    synonyms: ['slim', 'slender', 'skinny'],
    collocations: ['thin line', 'thin layer', 'thin ice'],
    antonyms: [],
    spellingDistractors: ['tin', 'phin', 'thinn'],
  },
  {
    word: 'this',
    wordClass: 'pronoun',
    level: 'a1',
    ipa: '/ðɪs/',
    stress: [1],
    syllables: ['this'],
    phonemes: ['dh', 'i', 's'],
    definition: 'Used to identify a specific person or thing close at hand or being indicated.',
    example: 'This is my favorite book in the library.',
    wordFamily: ['these'],
    synonyms: ['here'],
    collocations: ['this one', 'this time', 'like this'],
    antonyms: [],
    spellingDistractors: ['dis', 'tis', 'thiss'],
  },
  {
    word: 'correct',
    wordClass: 'adjective',
    level: 'b1',
    ipa: '/kəˈrekt/',
    stress: [0, 1],
    syllables: ['cor', 'rect'],
    phonemes: ['k', 'uh', 'r', 'e', 'k', 't'],
    definition: 'Free from error; in accordance with fact or truth.',
    example: 'Make sure all your answers are correct before submitting.',
    wordFamily: ['correctly', 'correction', 'incorrect'],
    synonyms: ['right', 'accurate', 'proper'],
    collocations: ['correct answer', 'correct procedure', 'politically correct'],
    antonyms: [],
    spellingDistractors: ['collect', 'corect', 'correkt'],
  },
  {
    word: 'office',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/ˈɒfɪs/',
    stress: [1, 0],
    syllables: ['of', 'fice'],
    phonemes: ['o', 'f', 'i', 's'],
    definition:
      'A room, set of rooms, or building used as a place for commercial, professional, or bureaucratic work.',
    example: 'He works at a high-tech software office in downtown.',
    wordFamily: ['officer', 'official', 'officially'],
    synonyms: ['headquarters', 'branch', 'bureau'],
    collocations: ['post office', 'box office', 'office hour'],
    antonyms: [],
    spellingDistractors: ['offis', 'ofice', 'offise'],
  },
  {
    word: 'wash',
    wordClass: 'verb',
    level: 'a1',
    ipa: '/wɒʃ/',
    stress: [1],
    syllables: ['wash'],
    phonemes: ['w', 'o', 'sh'],
    definition: 'Clean with water and, typically, soap or detergent.',
    example: 'Remember to wash your hands before eating dinner.',
    wordFamily: ['washing', 'washed', 'washer'],
    synonyms: ['clean', 'rinse', 'scrub'],
    collocations: ['wash hands', 'wash dishes', 'car wash'],
    antonyms: [],
    spellingDistractors: ['wat', 'wosh', 'washe'],
  },
  {
    word: 'hope',
    wordClass: 'verb',
    level: 'a2',
    ipa: '/həʊp/',
    stress: [1],
    syllables: ['hope'],
    phonemes: ['h', 'oh', 'p'],
    definition: 'Want something to happen or be the case, and think it is possible.',
    example: 'I hope that you will pass the English exam tomorrow.',
    wordFamily: ['hopeful', 'hopeless', 'hoping'],
    synonyms: ['wish', 'aspire', 'desire'],
    collocations: ['hope for', 'sincere hope', 'ray of hope'],
    antonyms: [],
    spellingDistractors: ['hop', 'hoap', 'hopee'],
  },

  // ─── Stage 1 Vowels Additions (10 words) ───
  {
    word: 'bat',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/bæt/',
    stress: [1],
    syllables: ['bat'],
    phonemes: ['b', 'ae', 't'],
    definition: 'An implement used for hitting the ball in games, or a nocturnal flying mammal.',
    example: 'He swung the baseball bat and hit a home run.',
    wordFamily: ['bats', 'batsman'],
    synonyms: ['club', 'paddle', 'stick'],
    collocations: ['baseball bat', 'cricket bat', 'wooden bat'],
    antonyms: [],
    spellingDistractors: ['bet', 'batt', 'bate'],
  },
  {
    word: 'hat',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/hæt/',
    stress: [1],
    syllables: ['hat'],
    phonemes: ['h', 'ae', 't'],
    definition: 'A shaped covering for the head worn for warmth, protection, or fashion.',
    example: 'She wore a straw hat to protect her face from the sun.',
    wordFamily: ['hats', 'hatter'],
    synonyms: ['cap', 'bonnet', 'helmet'],
    collocations: ['wear a hat', 'put on a hat', 'straw hat'],
    antonyms: [],
    spellingDistractors: ['het', 'hatt', 'hate'],
  },
  {
    word: 'bag',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/bæg/',
    stress: [1],
    syllables: ['bag'],
    phonemes: ['b', 'ae', 'g'],
    definition: 'A flexible container with an opening at the top, used for carrying things.',
    example: 'He packed his school books into his new backpack bag.',
    wordFamily: ['bags', 'baggage', 'backpack'],
    synonyms: ['sack', 'pouch', 'pack'],
    collocations: ['shopping bag', 'paper bag', 'plastic bag'],
    antonyms: [],
    spellingDistractors: ['beg', 'bagg', 'bage'],
  },
  {
    word: 'sad',
    wordClass: 'adjective',
    level: 'a1',
    ipa: '/sæd/',
    stress: [1],
    syllables: ['sad'],
    phonemes: ['s', 'ae', 'd'],
    definition: 'Feeling or showing sorrow; unhappy.',
    example: 'She felt very sad when her favorite pet ran away.',
    wordFamily: ['sadly', 'sadness', 'sadden'],
    synonyms: ['unhappy', 'gloomy', 'sorrowful'],
    collocations: ['feel sad', 'sad story', 'sad news'],
    antonyms: [],
    spellingDistractors: ['sed', 'sadd', 'sade'],
  },
  {
    word: 'man',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/mæn/',
    stress: [1],
    syllables: ['man'],
    phonemes: ['m', 'ae', 'n'],
    definition: 'An adult human male.',
    example: 'The tall man was walking down the quiet street.',
    wordFamily: ['men', 'manly', 'manhood'],
    synonyms: ['gentleman', 'guy', 'fellow'],
    collocations: ['young man', 'old man', 'wise man'],
    antonyms: [],
    spellingDistractors: ['men', 'mann', 'mane'],
  },
  {
    word: 'pen',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/pen/',
    stress: [1],
    syllables: ['pen'],
    phonemes: ['p', 'e', 'n'],
    definition: 'An instrument for writing or drawing with ink.',
    example: 'He wrote the letter using a blue ink pen.',
    wordFamily: ['pens', 'pencil'],
    synonyms: ['quill', 'marker'],
    collocations: ['ballpoint pen', 'ink pen', 'write with a pen'],
    antonyms: [],
    spellingDistractors: ['pan', 'penn', 'pene'],
  },
  {
    word: 'leg',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/leg/',
    stress: [1],
    syllables: ['leg'],
    phonemes: ['l', 'e', 'g'],
    definition: 'Each of the limbs on which a person or animal stands and moves.',
    example: 'She hurt her left leg while running in the race.',
    wordFamily: ['legs', 'leggings'],
    synonyms: ['limb', 'shank'],
    collocations: ['broken leg', 'left leg', 'stretch legs'],
    antonyms: [],
    spellingDistractors: ['lag', 'legg', 'lege'],
  },
  {
    word: 'hen',
    wordClass: 'noun',
    level: 'a2',
    ipa: '/hen/',
    stress: [1],
    syllables: ['hen'],
    phonemes: ['h', 'e', 'n'],
    definition: 'A female bird, especially of a domestic fowl.',
    example: 'The brown hen laid a fresh egg this morning.',
    wordFamily: ['hens', 'chicken'],
    synonyms: ['fowl', 'poultry'],
    collocations: ['farm hen', 'hen house', 'laying hen'],
    antonyms: [],
    spellingDistractors: ['han', 'henn', 'hene'],
  },
  {
    word: 'wet',
    wordClass: 'adjective',
    level: 'a1',
    ipa: '/wet/',
    stress: [1],
    syllables: ['wet'],
    phonemes: ['w', 'e', 't'],
    definition: 'Covered or saturated with water or another liquid.',
    example: 'Be careful not to step on the wet grass.',
    wordFamily: ['wetness', 'wetly', 'wetter'],
    synonyms: ['damp', 'moist', 'soaked'],
    collocations: ['wet weather', 'wet paint', 'wet cloth'],
    antonyms: [],
    spellingDistractors: ['wat', 'wett', 'wete'],
  },
  {
    word: 'nest',
    wordClass: 'noun',
    level: 'a2',
    ipa: '/nest/',
    stress: [1],
    syllables: ['nest'],
    phonemes: ['n', 'e', 's', 't'],
    definition: 'A structure or place made by a bird for laying eggs and sheltering its young.',
    example: 'The swallow built a muddy nest under the roof.',
    wordFamily: ['nests', 'nesting'],
    synonyms: ['roost', 'shelter', 'crush'],
    collocations: ['bird nest', 'build a nest', 'empty nest'],
    antonyms: [],
    spellingDistractors: ['nast', 'nestt', 'naste'],
  },

  // ─── Stage 2 Vowels Additions (15 words) ───
  {
    word: 'pin',
    wordClass: 'noun',
    level: 'a2',
    ipa: '/pɪn/',
    stress: [1],
    syllables: ['pin'],
    phonemes: ['p', 'i', 'n'],
    definition: 'A thin piece of metal with a sharp point, used for fastening things together.',
    example: 'She used a safety pin to hold the fabric in place.',
    wordFamily: ['pins', 'pincushion'],
    synonyms: ['needle', 'peg', 'fastener'],
    collocations: ['safety pin', 'push pin', 'hair pin'],
    antonyms: [],
    spellingDistractors: ['pen', 'pinn', 'pine'],
  },
  {
    word: 'pig',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/pɪg/',
    stress: [1],
    syllables: ['pig'],
    phonemes: ['p', 'i', 'g'],
    definition: 'An omnivorous hoofed domesticated mammal with a snout and a curly tail.',
    example: 'The friendly pig rolled around in the muddy puddle.',
    wordFamily: ['pigs', 'piglet'],
    synonyms: ['swine', 'hog', 'boar'],
    collocations: ['guinea pig', 'pig farm', 'wild pig'],
    antonyms: [],
    spellingDistractors: ['peg', 'pigg', 'pige'],
  },
  {
    word: 'big',
    wordClass: 'adjective',
    level: 'a1',
    ipa: '/bɪg/',
    stress: [1],
    syllables: ['big'],
    phonemes: ['b', 'i', 'g'],
    definition: 'Of considerable size, extent, or intensity.',
    example: 'They bought a big house with a huge garden.',
    wordFamily: ['bigger', 'biggest', 'bigness'],
    synonyms: ['large', 'huge', 'giant'],
    collocations: ['big house', 'big city', 'big deal'],
    antonyms: [],
    spellingDistractors: ['beg', 'bigg', 'bige'],
  },
  {
    word: 'dig',
    wordClass: 'verb',
    level: 'a2',
    ipa: '/dɪg/',
    stress: [1],
    syllables: ['dig'],
    phonemes: ['d', 'i', 'g'],
    definition: 'Break up and move earth with a spade or claws.',
    example: 'The dogs love to dig holes in the backyard.',
    wordFamily: ['digging', 'dug', 'digger'],
    synonyms: ['excavate', 'scoop', 'shovel'],
    collocations: ['dig a hole', 'dig deep', 'dig up'],
    antonyms: [],
    spellingDistractors: ['deg', 'digg', 'dige'],
  },
  {
    word: 'lip',
    wordClass: 'noun',
    level: 'a2',
    ipa: '/lɪp/',
    stress: [1],
    syllables: ['lip'],
    phonemes: ['l', 'i', 'p'],
    definition:
      'Either of the two fleshy parts which form the upper and lower edges of the opening of the mouth.',
    example: 'She bit her lip nervously before speaking.',
    wordFamily: ['lips', 'lipstick'],
    synonyms: ['brim', 'edge'],
    collocations: ['upper lip', 'lower lip', 'lip balm'],
    antonyms: [],
    spellingDistractors: ['lep', 'lipp', 'lipe'],
  },
  {
    word: 'dog',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/dɒg/',
    stress: [1],
    syllables: ['dog'],
    phonemes: ['d', 'o', 'g'],
    definition:
      'A common domesticated carnivorous mammal that typically has a long snout and a barking voice.',
    example: 'He walked his friendly dog around the neighborhood park.',
    wordFamily: ['dogs', 'puppy', 'doggy'],
    synonyms: ['hound', 'canine', 'mutt'],
    collocations: ['pet dog', 'walk the dog', 'guard dog'],
    antonyms: [],
    spellingDistractors: ['deg', 'dogg', 'doge'],
  },
  {
    word: 'box',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/bɒks/',
    stress: [1],
    syllables: ['box'],
    phonemes: ['b', 'o', 'k', 's'],
    definition: 'A container with a flat base and sides, typically square or rectangular.',
    example: 'She stored her old toys in a large cardboard box.',
    wordFamily: ['boxes', 'boxing'],
    synonyms: ['carton', 'chest', 'crate'],
    collocations: ['cardboard box', 'gift box', 'lunch box'],
    antonyms: [],
    spellingDistractors: ['bex', 'boxx', 'bokes'],
  },
  {
    word: 'fox',
    wordClass: 'noun',
    level: 'a2',
    ipa: '/fɒks/',
    stress: [1],
    syllables: ['fox'],
    phonemes: ['f', 'o', 'k', 's'],
    definition:
      'A wild carnivorous mammal of the dog family, known for its bushy tail and cleverness.',
    example: 'A red fox slipped quietly through the forest trees.',
    wordFamily: ['foxes', 'foxy'],
    synonyms: ['vixen', 'clever animal'],
    collocations: ['red fox', 'wild fox', 'clever fox'],
    antonyms: [],
    spellingDistractors: ['fex', 'foxx', 'fokes'],
  },
  {
    word: 'top',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/tɒp/',
    stress: [1],
    syllables: ['top'],
    phonemes: ['t', 'o', 'p'],
    definition: 'The highest or uppermost part, point, or surface of something.',
    example: 'We climbed up to the top of the steep hill.',
    wordFamily: ['tops', 'topper', 'topmost'],
    synonyms: ['peak', 'summit', 'apex'],
    collocations: ['top floor', 'on top of', 'at the top'],
    antonyms: [],
    spellingDistractors: ['tep', 'topp', 'tope'],
  },
  {
    word: 'pot',
    wordClass: 'noun',
    level: 'a2',
    ipa: '/tɒt/',
    stress: [1],
    syllables: ['pot'],
    phonemes: ['p', 'o', 't'],
    definition: 'A container, typically rounded, used for cooking, storage, or growing plants.',
    example: 'She planted a yellow flower in a small clay pot.',
    wordFamily: ['pots', 'pottery', 'potter'],
    synonyms: ['pan', 'vessel', 'jar'],
    collocations: ['cooking pot', 'flower pot', 'clay pot'],
    antonyms: [],
    spellingDistractors: ['pet', 'pott', 'pote'],
  },
  {
    word: 'bus',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/bʌs/',
    stress: [1],
    syllables: ['bus'],
    phonemes: ['b', 'u', 's'],
    definition: 'A large motor vehicle carrying passengers by road, typically serving the public.',
    example: 'She takes the school bus to class every morning.',
    wordFamily: ['buses', 'bus stop'],
    synonyms: ['coach', 'transit'],
    collocations: ['school bus', 'bus stop', 'catch the bus'],
    antonyms: [],
    spellingDistractors: ['bas', 'buss', 'buse'],
  },
  {
    word: 'bug',
    wordClass: 'noun',
    level: 'a2',
    ipa: '/bʌg/',
    stress: [1],
    syllables: ['bug'],
    phonemes: ['b', 'u', 'g'],
    definition: 'A small insect or creeping crawling invertebrate.',
    example: 'A little green bug was sitting on the leaf.',
    wordFamily: ['bugs', 'buggy'],
    synonyms: ['insect', 'beetle'],
    collocations: ['software bug', 'lady bug', 'bed bug'],
    antonyms: [],
    spellingDistractors: ['beg', 'bugg', 'buge'],
  },
  {
    word: 'sun',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/sʌn/',
    stress: [1],
    syllables: ['sun'],
    phonemes: ['s', 'u', 'n'],
    definition: 'The star around which the earth revolves, giving light and heat.',
    example: 'The sun was rising early over the ocean.',
    wordFamily: ['sunny', 'sunlight', 'sunflower'],
    synonyms: ['sol', 'daystar'],
    collocations: ['bright sun', 'sun exposure', 'morning sun'],
    antonyms: [],
    spellingDistractors: ['san', 'sunn', 'sune'],
  },
  {
    word: 'nut',
    wordClass: 'noun',
    level: 'a2',
    ipa: '/nʌt/',
    stress: [1],
    syllables: ['nut'],
    phonemes: ['n', 'u', 't'],
    definition: 'A fruit consisting of a hard shell around an edible kernel.',
    example: 'A squirrel was busy collecting a brown hazel nut.',
    wordFamily: ['nuts', 'nutty', 'peanut'],
    synonyms: ['kernel', 'seed'],
    collocations: ['cashew nut', 'peanut butter', 'crack a nut'],
    antonyms: [],
    spellingDistractors: ['net', 'nutt', 'nute'],
  },
  {
    word: 'tub',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/tʌb/',
    stress: [1],
    syllables: ['tub'],
    phonemes: ['t', 'u', 'b'],
    definition: 'A wide, open, flat-bottomed container, especially used for washing or bathing.',
    example: 'He relaxed in a warm bath tub full of soap bubbles.',
    wordFamily: ['tubs', 'bathtub'],
    synonyms: ['basin', 'vat', 'trough'],
    collocations: ['hot tub', 'bath tub', 'ice tub'],
    antonyms: [],
    spellingDistractors: ['teb', 'tubb', 'tube'],
  },

  // ─── Stage 3 Vowels Additions (20 words) ───
  {
    word: 'bee',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/biː/',
    stress: [1],
    syllables: ['bee'],
    phonemes: ['b', 'ee'],
    definition: 'A stinging winged insect which collects nectar and pollen, and makes honey.',
    example: 'A fuzzy yellow bee buzzed near the honey hive.',
    wordFamily: ['bees', 'honeybee', 'beeswax'],
    synonyms: ['honey maker', 'bumblebee'],
    collocations: ['honey bee', 'busy bee', 'bee sting'],
    antonyms: [],
    spellingDistractors: ['be', 'beee', 'bey'],
  },
  {
    word: 'tree',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/triː/',
    stress: [1],
    syllables: ['tree'],
    phonemes: ['t', 'r', 'ee'],
    definition:
      'A woody perennial plant, typically having a single stem or trunk growing to a considerable height.',
    example: 'We sat under the green shade of the oak tree.',
    wordFamily: ['trees', 'woodland'],
    synonyms: ['sapling', 'timber'],
    collocations: ['climb a tree', 'green tree', 'plant a tree'],
    antonyms: [],
    spellingDistractors: ['tre', 'treee', 'trey'],
  },
  {
    word: 'feet',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/fiːt/',
    stress: [1],
    syllables: ['feet'],
    phonemes: ['f', 'ee', 't'],
    definition: 'The plural form of foot; the lower extremities of the legs.',
    example: 'He washed his dirty feet after playing outside.',
    wordFamily: ['foot', 'football'],
    synonyms: ['paws', 'hooves'],
    collocations: ['bare feet', 'cold feet', 'on your feet'],
    antonyms: [],
    spellingDistractors: ['feat', 'fett', 'fete'],
  },
  {
    word: 'green',
    wordClass: 'adjective',
    level: 'a1',
    ipa: '/griːn/',
    stress: [1],
    syllables: ['green'],
    phonemes: ['g', 'r', 'ee', 'n'],
    definition: 'Of the color between blue and yellow in the spectrum; colored like grass.',
    example: 'The frogs jumped into the green marsh water.',
    wordFamily: ['greenish', 'greens'],
    synonyms: ['verdant', 'leafy'],
    collocations: ['green light', 'green grass', 'dark green'],
    antonyms: [],
    spellingDistractors: ['grean', 'gren', 'grene'],
  },
  {
    word: 'sleep',
    wordClass: 'verb',
    level: 'a1',
    ipa: '/sliːp/',
    stress: [1],
    syllables: ['sleep'],
    phonemes: ['s', 'l', 'ee', 'p'],
    definition: 'Be in a state of natural rest in which consciousness is suspended.',
    example: 'It is healthy to sleep for eight hours every night.',
    wordFamily: ['sleepy', 'sleeping', 'sleepless', 'slept'],
    synonyms: ['doze', 'rest', 'slumber'],
    collocations: ['go to sleep', 'fall asleep', 'deep sleep'],
    antonyms: [],
    spellingDistractors: ['sleap', 'slep', 'slepe'],
  },
  {
    word: 'star',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/stɑː(r)/',
    stress: [1],
    syllables: ['star'],
    phonemes: ['s', 't', 'ar'],
    definition:
      'A fixed luminous point in the night sky which is a large, remote incandescent body.',
    example: 'We looked up at a shining bright star in the dark sky.',
    wordFamily: ['stars', 'starlight', 'starfish'],
    synonyms: ['sun', 'luminary'],
    collocations: ['shooting star', 'bright star', 'star shape'],
    antonyms: [],
    spellingDistractors: ['ster', 'starr', 'stare'],
  },
  {
    word: 'park',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/pɑːk/',
    stress: [1],
    syllables: ['park'],
    phonemes: ['p', 'ar', 'k'],
    definition: 'A large public green area in a town, used for recreation.',
    example: 'The kids rode their bikes around the town park.',
    wordFamily: ['parking', 'parks'],
    synonyms: ['common', 'playground'],
    collocations: ['national park', 'car park', 'amusement park'],
    antonyms: [],
    spellingDistractors: ['perk', 'parkk', 'prake'],
  },
  {
    word: 'farm',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/fɑːm/',
    stress: [1],
    syllables: ['farm'],
    phonemes: ['f', 'ar', 'm'],
    definition: 'An area of land used for growing crops and rearing animals.',
    example: 'My grandparents live on a dairy farm with cows and horses.',
    wordFamily: ['farmer', 'farming', 'farmhouse'],
    synonyms: ['homestead', 'ranch', 'plantation'],
    collocations: ['dairy farm', 'organic farm', 'work on a farm'],
    antonyms: [],
    spellingDistractors: ['ferm', 'farmm', 'fram'],
  },
  {
    word: 'dark',
    wordClass: 'adjective',
    level: 'a1',
    ipa: '/dɑːk/',
    stress: [1],
    syllables: ['dark'],
    phonemes: ['d', 'ar', 'k'],
    definition: 'With little or no light.',
    example: 'The street was completely dark after the lights went out.',
    wordFamily: ['darkness', 'darkly', 'darken'],
    synonyms: ['gloomy', 'shadowy', 'dim'],
    collocations: ['dark night', 'dark blue', 'pitch dark'],
    antonyms: [],
    spellingDistractors: ['derk', 'darkk', 'drake'],
  },
  {
    word: 'art',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/ɑːt/',
    stress: [1],
    syllables: ['art'],
    phonemes: ['ar', 't'],
    definition: 'The expression or application of human creative skill and imagination.',
    example: 'She loves drawing and painting in art class.',
    wordFamily: ['artist', 'artistic', 'artwork'],
    synonyms: ['craft', 'design', 'creation'],
    collocations: ['modern art', 'art gallery', 'work of art'],
    antonyms: [],
    spellingDistractors: ['ert', 'artt', 'arte'],
  },
  {
    word: 'ball',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/bɔːl/',
    stress: [1],
    syllables: ['ball'],
    phonemes: ['b', 'aw', 'l'],
    definition: 'A round object used in game playing, such as tennis, football, or basketball.',
    example: 'The boy kicked the soccer ball into the goal net.',
    wordFamily: ['balls', 'ballroom'],
    synonyms: ['sphere', 'globe', 'orb'],
    collocations: ['soccer ball', 'tennis ball', 'bounce a ball'],
    antonyms: [],
    spellingDistractors: ['bol', 'balll', 'bal'],
  },
  {
    word: 'law',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/lɔː/',
    stress: [1],
    syllables: ['law'],
    phonemes: ['l', 'aw'],
    definition:
      'The system of rules which a particular country or community recognizes as regulating actions.',
    example: 'Drivers must obey the speed limit law.',
    wordFamily: ['lawyer', 'lawful', 'unlawful'],
    synonyms: ['rule', 'regulation', 'code'],
    collocations: ['break the law', 'obey the law', 'law enforcement'],
    antonyms: [],
    spellingDistractors: ['lawe', 'lor', 'lo'],
  },
  {
    word: 'saw',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/sɔː/',
    stress: [1],
    syllables: ['saw'],
    phonemes: ['s', 'aw'],
    definition:
      'A hand tool for cutting wood or other materials, typically having a toothed blade.',
    example: 'He used a sharp saw to cut the thick branch.',
    wordFamily: ['saws', 'sawdust'],
    synonyms: ['blade', 'cutter'],
    collocations: ['hand saw', 'chain saw', 'cut with a saw'],
    antonyms: [],
    spellingDistractors: ['sawe', 'sor', 'so'],
  },
  {
    word: 'draw',
    wordClass: 'verb',
    level: 'a1',
    ipa: '/drɔː/',
    stress: [1],
    syllables: ['draw'],
    phonemes: ['d', 'r', 'aw'],
    definition: 'Produce a picture or diagram by making lines and marks on paper.',
    example: 'The artist loves to draw pictures of animals.',
    wordFamily: ['drawing', 'drawn', 'drawer'],
    synonyms: ['sketch', 'paint', 'trace'],
    collocations: ['draw a picture', 'draw a line', 'draw attention'],
    antonyms: [],
    spellingDistractors: ['drawe', 'dror', 'dro'],
  },
  {
    word: 'fall',
    wordClass: 'verb',
    level: 'a1',
    ipa: '/fɔːl/',
    stress: [1],
    syllables: ['fall'],
    phonemes: ['f', 'aw', 'l'],
    definition: 'Move downward, typically rapidly and freely without control.',
    example: 'The autumn leaves fall from the trees onto the ground.',
    wordFamily: ['falling', 'fell', 'fallen'],
    synonyms: ['drop', 'tumble', 'descend'],
    collocations: ['fall down', 'fall asleep', 'fall in love'],
    antonyms: [],
    spellingDistractors: ['fol', 'falll', 'fal'],
  },
  {
    word: 'cool',
    wordClass: 'adjective',
    level: 'a1',
    ipa: '/kuːl/',
    stress: [1],
    syllables: ['cool'],
    phonemes: ['k', 'oo', 'l'],
    definition: 'Of or at a fairly low temperature, in a pleasant way.',
    example: 'A cool breeze blew through the open window.',
    wordFamily: ['coolness', 'coolly', 'cooler'],
    synonyms: ['chilly', 'fresh', 'breezy'],
    collocations: ['cool breeze', 'cool water', 'keep cool'],
    antonyms: [],
    spellingDistractors: ['col', 'cooll', 'cule'],
  },
  {
    word: 'pool',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/puːl/',
    stress: [1],
    syllables: ['pool'],
    phonemes: ['p', 'oo', 'l'],
    definition: 'A small area of still water, or an artificial pool for swimming.',
    example: 'We swam in the cool water of the swimming pool.',
    wordFamily: ['pools', 'swimming'],
    synonyms: ['pond', 'basin', 'lago'],
    collocations: ['swimming pool', 'pool party', 'puddle pool'],
    antonyms: [],
    spellingDistractors: ['pol', 'pooll', 'pule'],
  },
  {
    word: 'food',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/fuːd/',
    stress: [1],
    syllables: ['food'],
    phonemes: ['f', 'oo', 'd'],
    definition: 'Any nutritious substance that people or animals eat or drink.',
    example: 'We bought fresh food from the organic market.',
    wordFamily: ['foods', 'feed', 'fastfood'],
    synonyms: ['meal', 'nourishment', 'grub'],
    collocations: ['delicious food', 'fast food', 'fresh food'],
    antonyms: [],
    spellingDistractors: ['fod', 'foodd', 'fude'],
  },
  {
    word: 'spoon',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/spuːn/',
    stress: [1],
    syllables: ['spoon'],
    phonemes: ['s', 'p', 'oo', 'n'],
    definition:
      'An implement consisting of a small, shallow oval bowl with a long handle, used for eating or serving.',
    example: 'She ate her hot soup using a silver spoon.',
    wordFamily: ['spoons', 'spoonful'],
    synonyms: ['ladle', 'scoop'],
    collocations: ['soup spoon', 'teaspoon', 'wooden spoon'],
    antonyms: [],
    spellingDistractors: ['spon', 'spoonn', 'spune'],
  },
  {
    word: 'blue',
    wordClass: 'adjective',
    level: 'a1',
    ipa: '/bluː/',
    stress: [1],
    syllables: ['blue'],
    phonemes: ['b', 'l', 'oo'],
    definition: 'Of a color intermediate between green and violet, as of the sky on a clear day.',
    example: 'She wore a beautiful blue dress to the party.',
    wordFamily: ['bluish', 'bluebird'],
    synonyms: ['azure', 'sky-blue'],
    collocations: ['blue sky', 'light blue', 'dark blue'],
    antonyms: [],
    spellingDistractors: ['blew', 'bloo', 'blu'],
  },

  // ─── Stage 4 Vowels Additions (5 words) ───
  {
    word: 'cake',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/keɪk/',
    stress: [1],
    syllables: ['cake'],
    phonemes: ['k', 'ay', 'k'],
    definition:
      'An item of sweet food made from flour, liquid, eggs, and sugar, baked and decorated.',
    example: 'She baked a delicious chocolate birthday cake.',
    wordFamily: ['cakes', 'cupcake'],
    synonyms: ['pastry', 'tart'],
    collocations: ['birthday cake', 'chocolate cake', 'slice of cake'],
    antonyms: [],
    spellingDistractors: ['cak', 'cayk', 'cakee'],
  },
  {
    word: 'lake',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/leɪk/',
    stress: [1],
    syllables: ['lake'],
    phonemes: ['l', 'ay', 'k'],
    definition: 'A large body of water surrounded by land.',
    example: 'We rented a small boat to row on the lake.',
    wordFamily: ['lakes', 'lakeside'],
    synonyms: ['pond', 'lagoon', 'pool'],
    collocations: ['freshwater lake', 'lake shore', 'lake side'],
    antonyms: [],
    spellingDistractors: ['lak', 'layk', 'lakee'],
  },
  {
    word: 'rain',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/reɪn/',
    stress: [1],
    syllables: ['rain'],
    phonemes: ['r', 'ay', 'n'],
    definition: 'Moisture condensed from the atmosphere that falls visible in separate drops.',
    example: 'Heavy rain fell from the dark grey clouds.',
    wordFamily: ['rainy', 'rainbow', 'raincoat', 'raining'],
    synonyms: ['shower', 'downpour', 'drizzle'],
    collocations: ['heavy rain', 'acid rain', 'rain drop'],
    antonyms: [],
    spellingDistractors: ['ran', 'rayn', 'raine'],
  },
  {
    word: 'train',
    wordClass: 'noun',
    level: 'a1',
    ipa: '/treɪn/',
    stress: [1],
    syllables: ['train'],
    phonemes: ['t', 'r', 'ay', 'n'],
    definition: 'A series of connected railway carriages or wagons moved by a locomotive.',
    example: 'The train arrived exactly on time at the station.',
    wordFamily: ['trains', 'trainer', 'training'],
    synonyms: ['express', 'railway'],
    collocations: ['steam train', 'train station', 'board the train'],
    antonyms: [],
    spellingDistractors: ['tran', 'trayn', 'traine'],
  },
  {
    word: 'play',
    wordClass: 'verb',
    level: 'a1',
    ipa: '/pleɪ/',
    stress: [1],
    syllables: ['play'],
    phonemes: ['p', 'l', 'ay'],
    definition: 'Engage in activity for enjoyment and recreation rather than a serious purpose.',
    example: 'The kids like to play tags on the grass field.',
    wordFamily: ['player', 'playing', 'playful', 'playground'],
    synonyms: ['recreate', 'amuse', 'fun'],
    collocations: ['play soccer', 'play games', 'play music'],
    antonyms: [],
    spellingDistractors: ['pley', 'plae', 'plai'],
  },

  // ─── B1+ Expansion (12 words for CEFR test depth) ───
  {
    word: 'journey',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/ˈdʒɜːni/',
    stress: [1, 0],
    syllables: ['jour', 'ney'],
    phonemes: ['dz', 'er', 'n', 'ee'],
    definition:
      'An act of traveling from one place to another, especially a long or challenging one.',
    example: 'The train journey through the mountains was breathtaking.',
    wordFamily: ['journeys', 'journeyman'],
    synonyms: ['trip', 'voyage', 'expedition'],
    collocations: ['long journey', 'return journey', 'journey time'],
    antonyms: [],
    spellingDistractors: ['jerney', 'jorney', 'journy'],
  },
  {
    word: 'neighbor',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/ˈneɪbə(r)/',
    stress: [1, 0],
    syllables: ['neigh', 'bor'],
    phonemes: ['n', 'ay', 'b', 'uh'],
    definition: 'A person living near or next door to another.',
    example: 'Our friendly neighbor helped us carry the groceries inside.',
    wordFamily: ['neighbors', 'neighborhood', 'neighboring'],
    synonyms: ['resident', 'local', 'nearby'],
    collocations: ['next-door neighbor', 'good neighbor', 'neighbor country'],
    antonyms: [],
    spellingDistractors: ['naybor', 'nebor', 'neibor'],
  },
  {
    word: 'pleasure',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/ˈpleʒə(r)/',
    stress: [1, 0],
    syllables: ['plea', 'sure'],
    phonemes: ['p', 'l', 'e', 'zh', 'uh'],
    definition: 'A feeling of happy satisfaction and enjoyment.',
    example: 'It was a great pleasure to meet your family last night.',
    wordFamily: ['pleasurable', 'pleasantly'],
    synonyms: ['joy', 'delight', 'satisfaction'],
    collocations: ['my pleasure', 'take pleasure in', 'pleasure trip'],
    antonyms: [],
    spellingDistractors: ['plesure', 'plezure', 'pleashure'],
  },
  {
    word: 'machine',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/məˈʃiːn/',
    stress: [0, 1],
    syllables: ['ma', 'chine'],
    phonemes: ['m', 'uh', 'sh', 'ee', 'n'],
    definition:
      'An apparatus using mechanical power and having several parts, each with a definite function.',
    example: 'The washing machine broke down and flooded the laundry room.',
    wordFamily: ['machinery', 'machinist', 'mechanical'],
    synonyms: ['appliance', 'engine', 'device'],
    collocations: ['washing machine', 'sewing machine', 'vending machine'],
    antonyms: [],
    spellingDistractors: ['masheen', 'machin', 'mashine'],
  },
  {
    word: 'character',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/ˈkærəktə(r)/',
    stress: [1, 0, 0],
    syllables: ['char', 'ac', 'ter'],
    phonemes: ['k', 'ae', 'r', 'uh', 'k', 't', 'uh'],
    definition: 'The mental and moral qualities distinctive to an individual.',
    example: 'Her kind character made her beloved by everyone in school.',
    wordFamily: ['characteristic', 'characterize', 'characterless'],
    synonyms: ['personality', 'nature', 'temperament'],
    collocations: ['strong character', 'main character', 'good character'],
    antonyms: [],
    spellingDistractors: ['caracter', 'charackter', 'karacter'],
  },
  {
    word: 'achieve',
    wordClass: 'verb',
    level: 'b2',
    ipa: '/əˈtʃiːv/',
    stress: [0, 1],
    syllables: ['a', 'chieve'],
    phonemes: ['uh', 'ch', 'ee', 'v'],
    definition: 'Reach or attain by effort, especially a goal or desired outcome.',
    example: 'She worked hard to achieve her dream of becoming a doctor.',
    wordFamily: ['achievement', 'achievable', 'achiever'],
    synonyms: ['accomplish', 'attain', 'reach'],
    collocations: ['achieve success', 'achieve a goal', 'achieve results'],
    antonyms: [],
    spellingDistractors: ['acheeve', 'acheive', 'achive'],
  },
  {
    word: 'treasure',
    wordClass: 'noun',
    level: 'b2',
    ipa: '/ˈtreʒə(r)/',
    stress: [1, 0],
    syllables: ['trea', 'sure'],
    phonemes: ['t', 'r', 'e', 'zh', 'uh'],
    definition: 'A collection of precious items, such as gold, jewels, or valuable artifacts.',
    example: 'The pirates buried their treasure on a remote deserted island.',
    wordFamily: ['treasures', 'treasury', 'treasure hunt'],
    synonyms: ['riches', 'wealth', 'hoard'],
    collocations: ['buried treasure', 'treasure chest', 'hidden treasure'],
    antonyms: [],
    spellingDistractors: ['tresure', 'trezure', 'treshure'],
  },
  {
    word: 'enormous',
    wordClass: 'adjective',
    level: 'b2',
    ipa: '/ɪˈnɔːməs/',
    stress: [0, 1, 0],
    syllables: ['e', 'nor', 'mous'],
    phonemes: ['i', 'n', 'aw', 'm', 'uh', 's'],
    definition: 'Very large in size, quantity, or extent.',
    example: 'The enormous whale surfaced briefly then dove back into the deep ocean.',
    wordFamily: ['enormously', 'enormousness'],
    synonyms: ['huge', 'gigantic', 'immense'],
    collocations: ['enormous amount', 'enormous size', 'enormous pressure'],
    antonyms: [],
    spellingDistractors: ['enormus', 'enormas', 'inormous'],
  },
  {
    word: 'knowledge',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/ˈnɒlɪdʒ/',
    stress: [1, 0],
    syllables: ['knowl', 'edge'],
    phonemes: ['n', 'o', 'l', 'i', 'dz'],
    definition: 'Facts, information, and skills acquired through experience or education.',
    example: 'Having knowledge of English opens many career doors.',
    wordFamily: ['knowledgeable', 'known', 'unknown'],
    synonyms: ['understanding', 'wisdom', 'expertise'],
    collocations: ['general knowledge', 'common knowledge', 'knowledge base'],
    antonyms: [],
    spellingDistractors: ['nowledge', 'noledge', 'knowlege'],
  },
  {
    word: 'adventure',
    wordClass: 'noun',
    level: 'b2',
    ipa: '/ədˈventʃə(r)/',
    stress: [0, 1, 0],
    syllables: ['ad', 'ven', 'ture'],
    phonemes: ['uh', 'd', 'v', 'e', 'n', 'ch', 'uh'],
    definition: 'An unusual and exciting experience or activity.',
    example: 'They set off on a thrilling adventure to explore the Amazon rainforest.',
    wordFamily: ['adventurer', 'adventurous', 'adventures'],
    synonyms: ['exploit', 'quest', 'journey'],
    collocations: ['great adventure', 'adventure story', 'sense of adventure'],
    antonyms: [],
    spellingDistractors: ['adventur', 'adventuree', 'adventcher'],
  },
  {
    word: 'substance',
    wordClass: 'noun',
    level: 'b1',
    ipa: '/ˈsʌbstəns/',
    stress: [1, 0],
    syllables: ['sub', 'stance'],
    phonemes: ['s', 'u', 'b', 's', 't', 'uh', 'n', 's'],
    definition: 'A particular kind of matter with uniform physical properties.',
    example: 'A sticky green substance was oozing from the broken pipe.',
    wordFamily: ['substantial', 'substantially', 'substantive'],
    synonyms: ['material', 'matter', 'compound'],
    collocations: ['chemical substance', 'toxic substance', 'substance abuse'],
    antonyms: [],
    spellingDistractors: ['substence', 'substancee', 'substans'],
  },
  {
    word: 'relevant',
    wordClass: 'adjective',
    level: 'b2',
    ipa: '/ˈreləvənt/',
    stress: [1, 0, 0],
    syllables: ['rel', 'e', 'vant'],
    phonemes: ['r', 'e', 'l', 'uh', 'v', 'uh', 'n', 't'],
    definition: 'Closely connected or appropriate to what is being done or considered.',
    example: 'Make sure all your answers are relevant to the specific question asked.',
    wordFamily: ['relevance', 'relevantly', 'irrelevant'],
    synonyms: ['pertinent', 'applicable', 'germane'],
    collocations: ['relevant information', 'relevant experience', 'highly relevant'],
    antonyms: [],
    spellingDistractors: ['relevent', 'revelant', 'relefant'],
  },
];

const legacyKey = (w: WordData) => `${w.word.toLowerCase()}|${w.level}`;
const legacySet = new Set(LEGACY_WORDS.map(legacyKey));

const enrichedDeduped: WordData[] = [];
const enrichedSeen = new Set<string>();
for (const w of ENRICHED_WORDS) {
  const key = `${w.word.toLowerCase()}|${w.level}`;
  if (!legacySet.has(key) && !enrichedSeen.has(key)) {
    enrichedSeen.add(key);
    enrichedDeduped.push(w);
  }
}

export const WORDS: WordData[] = [...LEGACY_WORDS, ...enrichedDeduped];
