// AUTO-GENERATED by `npm run krulaw:build` — do not edit manually.
import type { LawDoc } from '../../types/krulaw';

// The cast is sound: TS JSON-module inference widens `kind` to string, but every
// emitted JSON was zod-validated (validate.ts) before being written.
/** Static-literal lazy loaders only — template-literal imports break webpack. */
export const registry: Record<string, () => Promise<LawDoc>> = {
  "national-education-act-2542": () => import('./laws/national-education-act-2542.json') as Promise<LawDoc>,
  "sample": () => import('./laws/sample.json') as Promise<LawDoc>,
};

/** Authored ref code (planned-laws.json `code` + LAW_CODE_ALIASES) → registry slug. */
export const codeToSlug: Record<string, string> = {
  "พ.ร.บ.การศึกษาแห่งชาติ 2542": "national-education-act-2542",
  "พ.ร.บ.การศึกษาภาคบังคับ 2545": "compulsory-education-act-2545",
  "พ.ร.บ.การจัดการศึกษาสำหรับคนพิการ 2551": "education-for-persons-with-disabilities-act-2551",
  "พ.ร.บ.การพัฒนาเด็กปฐมวัย 2562": "early-childhood-development-act-2562",
  "พ.ร.บ.คุ้มครองเด็ก 2546": "child-protection-act-2546",
  "พ.ร.บ.เงินเดือน เงินวิทยฐานะ เงินประจำตำแหน่ง 2547": "salary-and-allowances-act-2547",
  "พ.ร.บ.ระเบียบข้าราชการครูและบุคลากรทางการศึกษา 2547": "teachers-educational-personnel-civil-service-act-2547",
  "พ.ร.บ.ระเบียบบริหารราชการกระทรวงศึกษาธิการ 2546": "ministry-of-education-administration-act-2546",
  "พ.ร.บ.สภาครูและบุคลากรทางการศึกษา 2546": "teachers-council-educational-personnel-act-2546",
  "พ.ร.บ.ส่งเสริมการเรียนรู้ 2566": "promotion-of-learning-act-2566",
  "พ.ร.บ.ข้าราชการครูฯ 2547": "teachers-educational-personnel-civil-service-act-2547",
};
