export interface LangEntry {
  th: { student: string; advanced: string };
  en: { student: string; advanced: string };
}

function entry(
  thStudent: string,
  enStudent: string,
  thAdvanced?: string,
  enAdvanced?: string,
): LangEntry {
  return {
    th: { student: thStudent, advanced: thAdvanced ?? thStudent },
    en: { student: enStudent, advanced: enAdvanced ?? enStudent },
  };
}

export const LANG: Record<string, LangEntry> = {
  /* === BOOT / BIOS === */
  "boot.title": entry("COMPUTER LAB BIOS v1.0", "COMPUTER LAB BIOS v1.0"),
  "boot.cpu": entry("CPU: PixelCore @ 1MHz", "CPU: PixelCore @ 1MHz"),
  "boot.ram": entry("RAM: 64KB OK", "RAM: 64KB OK"),
  "boot.hdd": entry("HDD: DETECTED", "HDD: DETECTED"),
  "boot.gpu": entry("GPU: Integrated Pixel Graphics", "GPU: Integrated Pixel Graphics"),
  "boot.start": entry("กด START เพื่อเริ่มต้น", "Press START to continue"),
  "boot.loading": entry("กำลังบูตระบบ...", "Booting system..."),
  "boot.dev": entry("โหมดนักพัฒนา: ปลดล็อกทุกด่าน!", "Dev Mode: All stages unlocked!"),

  /* === LOADING === */
  "loading": entry("กำลังโหลด...", "Loading..."),
  "loading.message": entry("กำลังเตรียมห้องแล็บ...", "Preparing the lab..."),
  "loading.sub": entry("กรุณารอสักครู่", "Please wait a moment"),
  "loading.preparing": entry("กำลังเตรียมอุปกรณ์...", "Preparing components..."),
  "loading.calibrating": entry("กำลังปรับเทียบระบบ...", "Calibrating system..."),

  /* === TOPBAR === */
  "topbar.fullscreen": entry("เต็มจอ", "Fullscreen", "เต็มจอ", "Fullscreen"),
  "topbar.lang": entry("ภาษา", "Language", "ภาษา", "Language"),
  "topbar.mode": entry("โหมด", "Mode", "โหมด", "Mode"),
  "topbar.quality": entry("คุณภาพ", "Quality", "คุณภาพ", "Quality"),
  "topbar.mute": entry("เสียง", "Sound", "เสียง", "Sound"),
  "topbar.back": entry("กลับ", "Back", "กลับ", "Back"),
  "topbar.mode.student": entry("นักเรียน", "Student", "นักเรียน", "Student"),
  "topbar.mode.advanced": entry("ขั้นสูง", "Advanced", "ขั้นสูง", "Advanced"),
  "topbar.settings": entry("ตั้งค่า", "Settings", "ตั้งค่า", "Settings"),
  "topbar.volume": entry("ระดับเสียง", "Volume", "ระดับเสียง", "Volume"),

  /* === MENU === */
  "menu.title": entry("COMPUTER LAB", "COMPUTER LAB"),
  "menu.subtitle": entry("เรียนรู้โลกของคอมพิวเตอร์", "Explore the World of Computers"),
  "menu.start": entry("เริ่มต้น", "START"),
  "menu.resume": entry("เล่นต่อ", "Resume"),
  "menu.stage": entry("ด่าน", "Stage"),
  "menu.locked": entry("ปลดล็อคด่านก่อนหน้า!", "Complete previous stage!"),
  "menu.stars": entry("ดาว", "Stars"),
  "menu.clear": entry("ล้างข้อมูล", "Clear Progress"),
  "menu.confirm": entry("แน่ใจหรือไม่? ข้อมูลทั้งหมดจะถูกลบ", "Are you sure? All progress will be lost."),
  "menu.confirm.yes": entry("ใช่, ลบเลย", "Yes, delete"),
  "menu.confirm.no": entry("ยกเลิก", "Cancel"),

  /* === STAGE 1: HARDWARE === */
  "stage1.title": entry("เรียนรู้ฮาร์ดแวร์", "Learn Hardware"),
  "stage1.instruction": entry("จัดอุปกรณ์ลงหมวดที่ถูกต้อง", "Sort components into correct categories", "จับคู่ชิ้นส่วนฮาร์ดแวร์กับหมวดหมู่ที่ถูกต้องทางเทคนิค", "Match hardware components to their technical categories"),
  "stage1.instruction.tap": entry("แตะหมวดที่ถูกต้อง", "Tap the correct category", "เลือกหมวดหมู่ที่เหมาะสมตามหน้าที่ของชิ้นส่วน", "Select the category matching the component's function"),
  "stage1.correct": entry("ถูกต้อง!", "Correct!"),
  "stage1.wrong": entry("ผิด ลองใหม่อีกครั้ง", "Wrong, try again"),
  "stage1.complete": entry("เรียนรู้ฮาร์ดแวร์สำเร็จ!", "Hardware Learning Complete!"),
  "stage1.continue": entry("เล่นต่อหรือเปลี่ยนด่าน?", "Continue or change stage?"),

  "hardware.input": entry("อุปกรณ์นำเข้า", "Input Devices", "อุปกรณ์รับข้อมูลเข้า", "Input Devices"),
  "hardware.output": entry("อุปกรณ์ส่งออก", "Output Devices", "อุปกรณ์แสดงผลลัพธ์", "Output Devices"),
  "hardware.processing": entry("อุปกรณ์ประมวลผล", "Processing Devices", "หน่วยประมวลผลกลาง", "Processing Units"),
  "hardware.storage": entry("อุปกรณ์จัดเก็บ", "Storage Devices", "หน่วยความจำและอุปกรณ์จัดเก็บ", "Memory & Storage"),

  "hw.cpu": entry("CPU", "CPU", "หน่วยประมวลผลกลาง (CPU)", "Central Processing Unit (CPU)"),
  "hw.gpu": entry("GPU", "GPU", "หน่วยประมวลผลกราฟิก (GPU)", "Graphics Processing Unit (GPU)"),
  "hw.motherboard": entry("เมนบอร์ด", "Motherboard", "แผงวงจรหลัก (Motherboard)", "Main Circuit Board (Motherboard)"),
  "hw.ram": entry("RAM", "RAM", "หน่วยความจำแรม (RAM)", "Random Access Memory (RAM)"),
  "hw.hdd": entry("ฮาร์ดดิสก์", "HDD", "ฮาร์ดดิสก์ไดรฟ์ (HDD)", "Hard Disk Drive (HDD)"),
  "hw.ssd": entry("SSD", "SSD", "โซลิดสเตตไดรฟ์ (SSD)", "Solid State Drive (SSD)"),
  "hw.usb": entry("USB", "USB", "แฟลชไดรฟ์ USB", "USB Flash Drive"),
  "hw.sd": entry("การ์ด SD", "SD Card", "การ์ดหน่วยความจำ SD", "Secure Digital (SD) Card"),
  "hw.keyboard": entry("คีย์บอร์ด", "Keyboard", "แป้นพิมพ์", "Keyboard"),
  "hw.mouse": entry("เมาส์", "Mouse", "เมาส์", "Mouse"),
  "hw.monitor": entry("จอภาพ", "Monitor", "จอภาพ", "Monitor"),
  "hw.printer": entry("ปริ้นเตอร์", "Printer", "เครื่องพิมพ์", "Printer"),
  "hw.speaker": entry("ลำโพง", "Speaker", "ลำโพง", "Speaker"),
  "hw.projector": entry("โปรเจคเตอร์", "Projector", "เครื่องฉายภาพ", "Projector"),
  "hw.headphones": entry("หูฟัง", "Headphones", "หูฟัง", "Headphones"),
  "hw.mic": entry("ไมโครโฟน", "Microphone", "ไมโครโฟน", "Microphone"),
  "hw.scanner": entry("สแกนเนอร์", "Scanner", "เครื่องสแกนเอกสาร", "Scanner"),
  "hw.webcam": entry("เว็บแคม", "Webcam", "กล้องเว็บแคม", "Webcam"),
  "hw.joystick": entry("จอยสติ๊ก", "Joystick", "อุปกรณ์ควบคุมเกม", "Joystick"),
  "hw.robotarm": entry("แขนหุ่นยนต์", "Robot Arm", "แขนกล", "Robot Arm"),

  /* === STAGE 2: SOFTWARE === */
  "stage2.title": entry("เรียนรู้ซอฟต์แวร์", "Learn Software"),
  "stage2.instruction": entry("จัดเรียงซอฟต์แวร์เป็น OS หรือ App", "Sort software into OS or App", "จำแนกประเภทของซอฟต์แวร์ตามหน้าที่", "Classify software by their function"),
  "stage2.tap": entry("แตะ OS หรือ App", "Tap OS or App", "เลือกระบบปฏิบัติการหรือแอปพลิเคชัน", "Choose Operating System or Application"),
  "stage2.correct": entry("ถูกต้อง!", "Correct!"),
  "stage2.wrong": entry("ผิด ลองใหม่!", "Wrong, try again!"),
  "stage2.complete": entry("เรียนรู้ซอฟต์แวร์สำเร็จ!", "Software Learning Complete!"),
  "stage2.continue": entry("เก่งมาก! ทำต่อไหม?", "Great! Keep going?"),

  "software.os": entry("ระบบปฏิบัติการ", "Operating System", "ระบบปฏิบัติการ (OS)", "Operating System (OS)"),
  "software.app": entry("แอปพลิเคชัน", "Application", "โปรแกรมประยุกต์", "Application Software"),

  "sw.windows": entry("Windows", "Windows"),
  "sw.macos": entry("macOS", "macOS"),
  "sw.linux": entry("Linux", "Linux"),
  "sw.android": entry("Android", "Android"),
  "sw.ios": entry("iOS", "iOS"),
  "sw.chromeos": entry("ChromeOS", "ChromeOS"),
  "sw.word": entry("Microsoft Word", "Microsoft Word"),
  "sw.excel": entry("Microsoft Excel", "Microsoft Excel"),
  "sw.photoshop": entry("Photoshop", "Photoshop"),
  "sw.vscode": entry("VS Code", "VS Code"),
  "sw.chrome": entry("Google Chrome", "Google Chrome"),
  "sw.spotify": entry("Spotify", "Spotify"),
  "sw.zoom": entry("Zoom", "Zoom"),
  "sw.calculator": entry("เครื่องคิดเลข", "Calculator"),
  "sw.calendar": entry("ปฏิทิน", "Calendar"),
  "sw.clock": entry("นาฬิกา", "Clock"),

  /* === STAGE 3: WORKFLOW === */
  "stage3.title": entry("เรียนรู้การทำงานของคอมพิวเตอร์", "Learn Computer Workflow"),
  "stage3.instruction": entry("สำรวจวิธีการทำงานของคอมพิวเตอร์", "Explore how computers work"),
  "workflow.tab.explore": entry("สำรวจ", "Explore"),
  "workflow.tab.scenarios": entry("สถานการณ์จำลอง", "Scenarios"),
  "workflow.overview": entry("ภาพรวมระบบ", "System Overview"),
  "workflow.diagram": entry("Input → CPU ↔ RAM → Storage → Output", "Input → CPU ↔ RAM → Storage → Output"),
  "workflow.click.case": entry("แตะที่เคสเพื่อดูภายใน", "Click the case to see inside"),
  "workflow.click.motherboard": entry("แตะส่วนประกอบเพื่อดูข้อมูล", "Click a component for details"),

  "workflow.taskmanager": entry("ตัวจัดการงาน", "Task Manager"),
  "workflow.cpu": entry("CPU", "CPU"),
  "workflow.ram": entry("RAM", "RAM"),
  "workflow.storage": entry("STORAGE", "STORAGE"),
  "workflow.gpu": entry("GPU", "GPU"),
  "workflow.temp": entry("อุณหภูมิ", "Temp"),

  "scenario.normal": entry("การทำงานปกติ", "Normal Flow", "กระแสข้อมูลปกติ", "Normal Data Flow"),
  "scenario.normal.desc": entry("ข้อมูลเดินทาง Input→CPU→RAM→CPU→Output", "Data travels Input→CPU→RAM→CPU→Output", "ข้อมูลไหลผ่านเส้นทางมาตรฐานจากอุปกรณ์นำเข้าสู่หน่วยประมวลผลและส่งออก", "Data flows through the standard path from input to processing to output"),
  "scenario.cpu": entry("CPU โอเวอร์โหลด", "CPU Overload", "การทำงานเกินพิกัดของ CPU", "CPU Overload"),
  "scenario.cpu.desc": entry("CPU ทำทีละอย่าง RAM ช่วยพักข้อมูล", "CPU does one thing at a time. RAM buffers extras.", "เมื่อมีการส่งคำสั่งหลายคำสั่งพร้อมกัน CPU จะประมวลผลทีละคำสั่ง โดยอาศัย RAM เป็นตัวกลาง", "When multiple instructions arrive, the CPU processes one at a time using RAM as a buffer"),
  "scenario.ram": entry("RAM เต็ม", "RAM Full", "หน่วยความจำไม่เพียงพอ", "Insufficient Memory"),
  "scenario.ram.desc": entry("โปรแกรมมากไป = RAM เต็ม = เครื่องช้า", "Too many programs = full RAM = slow PC", "การเปิดโปรแกรมพร้อมกันมากเกินไปทำให้ RAM ไม่เพียงพอ ส่งผลให้เครื่องทำงานช้าลง", "Running too many programs simultaneously exhausts RAM, causing system slowdown"),
  "scenario.bottleneck": entry("คอขวด", "Bottleneck", "จุดคอขวดของระบบ", "System Bottleneck"),
  "scenario.bottleneck.desc": entry("ส่วนที่เร็วที่สุดรอส่วนที่ช้าที่สุด", "Fastest part waits for slowest part", "ประสิทธิภาพโดยรวมของระบบถูกจำกัดโดยส่วนประกอบที่ช้าที่สุด", "Overall system performance is limited by the slowest component"),
  "scenario.noram": entry("ไม่มี RAM", "No RAM", "ระบบไม่มีหน่วยความจำ RAM", "System without RAM"),
  "scenario.noram.desc": entry("ต้องมี RAM ถึงจะบูตได้ ถ้าไม่มีจะขึ้น BSOD", "RAM is required for boot — BSOD without it", "RAM เป็นส่วนประกอบจำเป็นสำหรับการเริ่มต้นระบบ หากไม่มีจะเกิดจอฟ้า (BSOD)", "RAM is essential for system boot; without it a Blue Screen of Death occurs"),
  "scenario.turbo": entry("โหมดเทอร์โบ", "Turbo Mode", "การเพิ่มความเร็วสัญญาณนาฬิกา", "Clock Speed Boost"),
  "scenario.turbo.desc": entry("ความเร็วสัญญาณนาฬิกาสูง = ทำงานต่อวินาทีมากขึ้น", "Higher clock speed = more work per second", "การเพิ่มความเร็วสัญญาณนาฬิกาของ CPU ช่วยให้ประมวลผลคำสั่งได้มากขึ้นต่อวินาที", "Increasing CPU clock speed enables more instructions per second"),
  "scenario.multitask": entry("การทำงานหลายอย่าง", "Multitasking", "การสลับบริบท", "Context Switching"),
  "scenario.multitask.desc": entry("CPU สลับงาน 1000 ครั้งต่อวินาที", "CPU context-switches 1000 times per second", "CPU สลับการทำงานระหว่างโปรแกรมต่างๆ หลายพันครั้งต่อวินาทีเพื่อให้ทำงานพร้อมกันได้", "The CPU switches between programs thousands of times per second to enable multitasking"),

  "scenario.start": entry("เริ่มสถานการณ์", "Start Scenario"),
  "scenario.restart": entry("เริ่มใหม่", "Restart"),
  "scenario.complete": entry("สถานการณ์สำเร็จ!", "Scenario Complete!"),
  "scenario.progress": entry("ความคืบหน้า", "Progress"),

  /* === STAGE 4: BUILD === */
  "stage4.title": entry("ประกอบเครื่องคอมพิวเตอร์", "Build a PC"),
  "stage4.instruction": entry("เลือกชิ้นส่วนและประกอบเครื่อง", "Select and assemble PC components", "เลือกชิ้นส่วนฮาร์ดแวร์และประกอบลงในเคสตามความยากที่เลือก", "Select hardware components and assemble them in the case at your chosen difficulty"),
  "stage4.select": entry("เลือกชิ้นส่วน", "Select a part", "เลือกชิ้นส่วนจากถาดด้านล่าง", "Select a part from the tray below"),
  "stage4.place": entry("วางในตำแหน่งที่ถูกต้อง", "Place in the correct slot", "วางชิ้นส่วนลงในตำแหน่งที่ถูกต้องบนเมนบอร์ด", "Place the component in the correct slot on the motherboard"),
  "stage4.correct": entry("ประกอบถูกต้อง!", "Correct assembly!"),
  "stage4.wrong": entry("ตำแหน่งไม่ถูกต้อง", "Wrong slot"),

  "build.difficulty.easy": entry("ง่าย: 4 ชิ้นส่วน", "Easy: 4 parts"),
  "build.difficulty.medium": entry("ปานกลาง: 6 ชิ้นส่วน", "Medium: 6 parts"),
  "build.difficulty.hard": entry("ยาก: 8 ชิ้นส่วน", "Hard: 8 parts"),
  "build.case": entry("เคสคอมพิวเตอร์", "PC Case"),
  "build.motherboard": entry("เมนบอร์ด", "Motherboard"),
  "build.parts": entry("ชิ้นส่วน", "Parts"),
  "build.complete": entry("ประกอบเครื่องสำเร็จ!", "PC Build Complete!"),
  "build.boot": entry("กำลังบูตเครื่อง...", "Booting up..."),

  "part.cpu": entry("CPU", "CPU"),
  "part.gpu": entry("GPU", "GPU"),
  "part.ramstick": entry("RAM", "RAM"),
  "part.hdd": entry("HDD", "HDD"),
  "part.psu": entry("PSU", "PSU"),
  "part.fan": entry("พัดลม CPU", "CPU Fan"),
  "part.cables": entry("สายเคเบิล", "Cables"),

  /* === STAGE 5: DIAGNOSIS === */
  "stage5.title": entry("วินิจฉัยปัญหา", "Fault Diagnosis"),
  "stage5.instruction": entry("ค้นหาปัญหาจากอาการ", "Find the problem from symptoms", "วิเคราะห์อาการเสียและระบุชิ้นส่วนที่บกพร่อง", "Analyze failure symptoms and identify the faulty component"),
  "stage5.lives": entry("ชีวิต", "Lives"),
  "stage5.hint": entry("คำใบ้", "Hint"),
  "stage5.hints": entry("คำใบ้ (เหลือ {n})", "Hints ({n} left)"),
  "stage5.correct": entry("ถูกต้อง! พบปัญหาแล้ว!", "Correct! Issue found!"),
  "stage5.wrong": entry("ผิด! เสียชีวิต 1", "Wrong! Lost 1 life"),
  "stage5.gameover": entry("เกมโอเวอร์! เฉลยคำตอบ", "Game Over! Revealing answer"),
  "stage5.complete": entry("วินิจฉัยครบ 20 ข้อ!", "All 20 diagnoses complete!"),

  "diag.symptom1": entry("คอมพิวเตอร์ไม่เปิดติดเลย", "Computer won't turn on at all"),
  "diag.symptom2": entry("หน้าจอไม่แสดงแต่เครื่องทำงาน", "Screen shows nothing but PC sounds like it's running"),
  "diag.symptom3": entry("เครื่องเปิดแต่ขึ้น 'No Boot Device'", "Computer turns on but says 'No Boot Device'"),
  "diag.symptom4": entry("ขึ้น 'หน่วยความจำไม่เพียงพอ' บ่อย", "Keep getting 'Out of Memory' errors"),
  "diag.symptom5": entry("เครื่องดับหลังจาก 5 นาที CPU ร้อนมาก", "Computer turns off after 5 minutes — CPU is very hot"),
  "diag.symptom6": entry("เสียงดังผิดปกติจากเคส", "Unusual noise coming from the case"),
  "diag.symptom7": entry("ภาพกระตุกหรือมีจุดแปลกบนหน้าจอ", "Screen flickers or shows strange artifacts"),
  "diag.symptom8": entry("คีย์บอร์ดหรือเมาส์ไม่ทำงาน", "Keyboard or mouse not responding"),
  "diag.symptom9": entry("อินเทอร์เน็ตช้าหรือขาดหาย", "Internet is slow or disconnecting"),
  "diag.symptom10": entry("เครื่องปิดเองขณะเล่นเกม", "Computer shuts down while gaming"),
  "diag.symptom11": entry("พัดลมไม่หมุน", "Fan is not spinning"),
  "diag.symptom12": entry("มีกลิ่นไหม้จากเคส", "Burning smell from the case"),
  "diag.symptom13": entry("USB ไม่ทำงาน", "USB ports not working"),
  "diag.symptom14": entry("เสียงออกลำโพงไม่ดัง", "No sound from speakers"),
  "diag.symptom15": entry("เครื่องค้างบ่อย", "Computer freezes frequently"),
  "diag.symptom16": entry("แบตเตอรี่โน้ตบุ๊กหมดเร็ว", "Laptop battery drains quickly"),
  "diag.symptom17": entry("ไวไฟเชื่อมต่อไม่ได้", "WiFi won't connect"),
  "diag.symptom18": entry("จอภาพมีเส้นแนวตั้ง", "Vertical lines on monitor"),
  "diag.symptom19": entry("เครื่องช้าผิดปกติ", "Computer is unusually slow"),
  "diag.symptom20": entry("ไดรฟ์ซีดี/ดีวีดีไม่อ่านแผ่น", "CD/DVD drive not reading discs"),

  "diag.part.psu": entry("PSU (แหล่งจ่ายไฟ)", "PSU (Power Supply)"),
  "diag.part.gpu": entry("GPU (การ์ดจอ)", "GPU (Graphics Card)"),
  "diag.part.storage": entry("HDD/SSD (ฮาร์ดดิสก์)", "HDD/SSD (Storage Drive)"),
  "diag.part.ram": entry("RAM (หน่วยความจำ)", "RAM (Memory)"),
  "diag.part.fan": entry("พัดลม CPU", "CPU Fan"),
  "diag.part.fan.case": entry("พัดลมเคส", "Case Fan"),
  "diag.part.cpu": entry("CPU", "CPU"),
  "diag.part.keyboard": entry("คีย์บอร์ด", "Keyboard"),
  "diag.part.mouse": entry("เมาส์", "Mouse"),
  "diag.part.network": entry("การ์ดเครือข่าย", "Network Card"),
  "diag.part.motherboard": entry("เมนบอร์ด", "Motherboard"),
  "diag.part.usb": entry("พอร์ต USB", "USB Controller"),
  "diag.part.speaker": entry("การ์ดเสียง", "Sound Card"),
  "diag.part.battery": entry("แบตเตอรี่", "Battery"),
  "diag.part.wifi": entry("การ์ดไวไฟ", "WiFi Card"),
  "diag.part.monitor": entry("จอภาพ", "Monitor"),
  "diag.part.drive": entry("ไดรฟ์ CD/DVD", "CD/DVD Drive"),

  /* === VICTORY === */
  "victory.title": entry("ผ่านด่าน!", "Stage Complete!"),
  "victory.continue": entry("ต่อไป", "Continue"),
  "victory.replay": entry("เล่นอีกครั้ง", "Replay"),
  "victory.stars": entry("ดาวที่ได้รับ", "Stars Earned"),
  "victory.perfect": entry("สมบูรณ์แบบ! ได้ 3 ดาว!", "Perfect! 3 Stars!"),
  "victory.good": entry("เยี่ยม! ได้ 2 ดาว", "Great! 2 Stars"),
  "victory.ok": entry("ผ่าน! ได้ 1 ดาว", "Pass! 1 Star"),
  "victory.card": entry("การ์ดความรู้", "Knowledge Card"),
  "victory.card.new": entry("ได้รับการ์ดใหม่!", "New card unlocked!"),
  "victory.all.complete": entry("ยินดีด้วย! คุณผ่านทุกด่านแล้ว!", "Congratulations! All stages complete!"),

  /* === KNOWLEDGE CARDS === */
  "card.speed": entry("⚡ ความเร็วแสง", "⚡ Speed of Light"),
  "card.speed.desc": entry("ข้อมูลเดินทางใกล้ความเร็วแสงในคอมพิวเตอร์!", "Data travels near the speed of light inside your computer!"),
  "card.cpu": entry("🔥 CPU จำกัด", "🔥 CPU Limits"),
  "card.cpu.desc": entry("CPU 3GHz ทำ 3 พันล้านคำสั่งต่อวินาที!", "A 3GHz CPU does 3 billion operations per second!"),
  "card.ram": entry("💾 RAM สำคัญ", "💾 RAM Matters"),
  "card.ram.desc": entry("ปิดโปรแกรมที่ไม่ใช้ช่วยเพิ่ม RAM ทำให้เครื่องเร็ว!", "Closing unused programs frees RAM and makes your PC faster!"),
  "card.slow": entry("🐌 จุดอ่อนในสายโซ่", "🐌 Chain Weakness"),
  "card.slow.desc": entry("คอมพิวเตอร์เร็วเท่าส่วนประกอบที่ช้าที่สุด!", "Your PC is only as fast as its SLOWEST component!"),
  "card.noram": entry("❌ ไม่มี RAM ไม่บูต", "❌ No RAM? No Boot"),
  "card.noram.desc": entry("ไม่มี RAM คอมพิวเตอร์ไม่สามารถบูตได้!", "Without RAM, a computer cannot even boot up!"),
  "card.turbo": entry("🚀 พลังเทอร์โบ", "🚀 Turbo Power"),
  "card.turbo.desc": entry("โอเวอร์คล็อกทำให้ CPU เร็วขึ้นแต่ร้อนขึ้น!", "Overclocking makes CPUs faster but generates more heat!"),
  "card.context": entry("🔄 ราชาแห่งการสลับ", "🔄 Context King"),
  "card.context.desc": entry("CPU สลับงาน 1000 ครั้งต่อวินาที!", "Your CPU switches between tasks 1000 times per second!"),
  "card.ssd": entry("💨 SSD vs HDD", "💨 SSD vs HDD"),
  "card.ssd.desc": entry("SSD เร็วกว่า HDD ถึง 100 เท่า!", "SSD is 100x faster than HDD!"),
  "card.freeze": entry("❄️ ระบบค้าง", "❄️ System Freeze"),
  "card.freeze.desc": entry("CPU หรือ RAM ทำงานหนักเกินไป ทำให้เครื่องค้าง!", "Overloaded CPU or RAM causes the system to freeze!"),
  "card.bsod": entry("💀 จอฟ้าแห่งความตาย", "💀 Blue Screen of Death"),
  "card.bsod.desc": entry("BSOD เกิดจากฮาร์ดแวร์หรือซอฟต์แวร์ทำงานผิดพลาดร้ายแรง!", "BSOD occurs from critical hardware or software failures!"),
  "card.overheat": entry("🌡️ เครื่องร้อนเกินไป", "🌡️ Overheating"),
  "card.overheat.desc": entry("CPU ร้อนเกิน 85°C ทำให้ระบบปิดตัวเองเพื่อป้องกัน!", "CPU over 85°C triggers automatic shutdown to prevent damage!"),
  "card.memleak": entry("🕳️ หน่วยความจำรั่ว", "🕳️ Memory Leak"),
  "card.memleak.desc": entry("โปรแกรมใช้ RAM แล้วไม่คืน ทำให้ RAM เต็ม!", "Programs that don't release RAM cause memory leaks!"),
  "card.slowpc": entry("🐢 คอมพิวเตอร์ช้า", "🐢 Slow PC"),
  "card.slowpc.desc": entry("HDD ช้า, RAM น้อย, CPU แก่ — สามสาเหตุหลักของคอมช้า!", "Slow HDD, low RAM, old CPU — three main causes of a slow PC!"),

  /* === SIMULATION UI KEYS (Phase B) === */
  "sim.send": entry("ส่ง", "Send"),
  "sim.reset": entry("รีเซ็ต", "Reset"),
  "sim.shape.circle": entry("ข้อความ", "Text"),
  "sim.shape.square": entry("ไฟล์", "File"),
  "sim.shape.diamond": entry("คำสั่ง", "Cmd"),
  "sim.input.placeholder": entry("พิมพ์ข้อความแล้วกดส่ง...", "Type text and press Send..."),
  "sim.concurrent": entry("พร้อมกัน", "Concurrent"),
  "sim.performance": entry("ประสิทธิภาพ", "Performance"),
  "sim.crash": entry("ขัดข้อง", "Crash"),
  "sim.ssd": entry("SSD", "SSD"),
  "sim.hdd": entry("HDD", "HDD"),
  "sim.interior": entry("ภายในเคส", "Inside Case"),
  "sim.interior.close": entry("ปิด", "Close"),
  "sim.desk": entry("โต๊ะทำงาน", "Desk View"),
  "sim.crash.title": entry("ระบบขัดข้อง!", "System Crash!"),
  "sim.crash.desc": entry("ตรวจพบความผิดปกติของระบบ", "System anomaly detected"),
  "sim.crash.fix": entry("คำแนะนำการแก้ไข", "Fix Tip"),

  /* Crash scenarios */
  "crash.freeze": entry("ระบบค้าง", "System Freeze"),
  "crash.freeze.desc": entry("CPU โอเวอร์โหลดและ RAM เต็ม—ระบบไม่ตอบสนอง", "CPU overload and full RAM—system becomes unresponsive"),
  "crash.bsod": entry("จอฟ้า (BSOD)", "Blue Screen"),
  "crash.bsod.desc": entry("RAM เสียหายหรือไม่มี—ระบบหยุดทำงาน", "Corrupted or missing RAM—system halts"),
  "crash.overheat": entry("ปิดเครื่องเพราะร้อน", "Overheat Shutdown"),
  "crash.overheat.desc": entry("CPU ร้อนเกินขีดจำกัด—ปิดเครื่องอัตโนมัติ", "CPU exceeds temperature limit—auto shutdown"),
  "crash.memleak": entry("หน่วยความจำรั่ว", "Memory Leak"),
  "crash.memleak.desc": entry("RAM ค่อยๆ เต็ม—ระบบช้าลงเรื่อยๆ", "RAM fills up gradually—system slows progressively"),
  "crash.slow": entry("เครื่องช้ามาก", "Extreme Slowness"),
  "crash.slow.desc": entry("HDD ช้ามาก—การดำเนินการแต่ละครั้งใช้เวลาหลายวินาที", "Very slow HDD—every operation takes seconds"),

  /* SSD vs HDD scenario */
  "scenario.ssd": entry("SSD vs HDD", "SSD vs HDD"),
  "scenario.ssd.desc": entry("เปรียบเทียบความเร็ว SSD และ HDD", "Compare SSD and HDD speed difference"),

  /* === COMPONENT MUSEUM === */
  "museum.title": entry("พิพิธภัณฑ์ส่วนประกอบ", "Component Museum"),
  "museum.progress": entry("ปลดล็อค {n}/{total}", "Unlocked {n}/{total}"),
  "museum.locked": entry("ต้องผ่านทุกด่านและสะสมการ์ดครบ", "Complete all stages and collect all cards"),
  "museum.unlocked": entry("ปลดล็อคแล้ว!", "Unlocked!"),

  /* === CERTIFICATE === */
  "cert.title": entry("ใบรับรอง", "Certificate"),
  "cert.line1": entry("ขอมอบใบรับรองนี้ให้แก่", "This certifies that"),
  "cert.line2": entry("ได้ผ่านการฝึกอบรม Computer Lab", "has completed Computer Lab training"),
  "cert.stars": entry("ดาวทั้งหมด", "Total Stars"),
  "cert.name": entry("พิมพ์ชื่อของคุณ", "Type your name"),
  "cert.save": entry("บันทึก", "Save"),

  /* === EASTER EGGS === */
  "easter.konami": entry("CHEATER!", "CHEATER!"),
  "easter.pong": entry("เกม Pong!", "Pong Game!"),
  "easter.snake": entry("เกม Snake!", "Snake Game!"),
  "easter.cat": entry("แมว!", "Cat!"),
  "easter.click": entry("คลิก {n} ครั้งเพื่อปลดล็อคเกมลับ", "Click {n} more times to unlock secret game"),

  /* === AUDIO === */
  "audio.track.menu": entry("เมนู", "Menu"),
  "audio.track.hardware": entry("ฮาร์ดแวร์", "Hardware"),
  "audio.track.software": entry("ซอฟต์แวร์", "Software"),
  "audio.track.workflow": entry("เวิร์กโฟลว์", "Workflow"),
  "audio.track.build": entry("ประกอบเครื่อง", "Build"),
  "audio.track.diagnosis": entry("วินิจฉัย", "Diagnosis"),
  "audio.track.victory": entry("ชัยชนะ", "Victory"),

  /* === ERRORS / UI === */
  "error.load": entry("เกิดข้อผิดพลาดในการโหลด", "Error loading data"),
  "error.save": entry("เกิดข้อผิดพลาดในการบันทึก", "Error saving data"),
  "error.unknown": entry("เกิดข้อผิดพลาดที่ไม่ทราบสาเหตุ", "An unknown error occurred"),
  "ui.ok": entry("ตกลง", "OK"),
  "ui.cancel": entry("ยกเลิก", "Cancel"),
  "ui.close": entry("ปิด", "Close"),
  "ui.retry": entry("ลองอีกครั้ง", "Retry"),
  "ui.skip": entry("ข้าม", "Skip"),
  "ui.next": entry("ถัดไป", "Next"),

  /* === WORKLOAD DESIGNER === */
  "workload.title": entry("ปริมาณงาน", "Workload"),
  "workload.add": entry("เพิ่มข้อมูล", "Add Data"),
  "workload.remove": entry("ลบ", "Remove"),
  "workload.concurrency": entry("ต่อวินาที", "/sec"),
  "workload.gpu": entry("ต้องใช้ GPU", "GPU"),
  "workload.apps": entry("แอปพลิเคชัน", "Apps"),
  "workload.app.add": entry("เปิด", "Open"),
  "workload.app.close": entry("ปิด", "Close"),
  "workload.ram": entry("RAM", "RAM"),
  "workload.apps.running": entry("แอปที่เปิดอยู่", "Running Apps"),
  "workload.datasets": entry("ชุดข้อมูล", "Datasets"),

  "workload.calculation": entry("คำนวณ", "Calculation"),
  "workload.text": entry("ข้อความ", "Text"),
  "workload.image": entry("รูปภาพ", "Image"),
  "workload.video": entry("วิดีโอ", "Video"),
  "workload.database": entry("ฐานข้อมูล", "Database"),
  "workload.web": entry("เว็บ", "Web"),
  "workload.ml": entry("ML", "ML"),
  "workload.compression": entry("บีบอัด", "Compression"),

  "app.vscode": entry("VS Code", "VS Code"),
  "app.chrome": entry("Chrome", "Chrome"),
  "app.photoshop": entry("Photoshop", "Photoshop"),
  "app.youtube": entry("YouTube", "YouTube"),
  "app.discord": entry("Discord", "Discord"),
  "app.spotify": entry("Spotify", "Spotify"),
  "app.calculator": entry("เครื่องคิดเลข", "Calculator"),
  "app.minecraft": entry("Minecraft", "Minecraft"),

  /* === SETTINGS PANEL === */
  "settings.title": entry("ตั้งค่า", "Settings"),
  "settings.concurrency": entry("ทำพร้อมกัน", "Concurrency"),
  "settings.resource": entry("ทรัพยากร", "Resource"),
  "settings.resource.light": entry("น้อย (<1GB)", "Light (<1GB)"),
  "settings.resource.medium": entry("ปานกลาง (1-3GB)", "Medium (1-3GB)"),
  "settings.resource.heavy": entry("หนัก (>3GB)", "Heavy (>3GB)"),
  "settings.workload": entry("ปริมาณงาน", "Workload"),
  "settings.datasize": entry("ขนาดข้อมูล", "Data Size"),

  /* === SPECS PANEL === */
  "specs.title": entry("ปรับสเปค", "Spec Adjustments"),
  "specs.cpu.cores": entry("CPU Cores", "CPU Cores"),
  "specs.cpu.clock": entry("CPU Clock", "CPU Clock"),
  "specs.ram.sticks": entry("RAM Sticks", "RAM Sticks"),
  "specs.ram.capacity": entry("RAM Capacity (GB)", "RAM Capacity (GB)"),
  "specs.gpu.cores": entry("GPU Cores", "GPU Cores"),
  "specs.gpu.vram": entry("GPU VRAM (GB)", "GPU VRAM (GB)"),
  "specs.ssd.read": entry("SSD Read (MB/s)", "SSD Read (MB/s)"),
  "specs.hdd.read": entry("HDD Read (MB/s)", "HDD Read (MB/s)"),

  /* === WIRE LABELS === */
  "wire.label.kbd": entry("KBD", "KBD"),
  "wire.label.hdmi": entry("HDMI", "HDMI"),

  /* === EMERGENT CRASH === */
  "crash.emergent.thermal": entry("ร้อนเกินไป—ลดภาระ CPU หรือเพิ่มพัดลม", "Overheating—reduce CPU load or increase fan"),
  "crash.emergent.ram": entry("RAM เต็ม—ปิดแอปหรืออัปเกรด RAM", "RAM full—close apps or upgrade RAM"),
  "crash.emergent.disk": entry("พื้นที่เต็ม—ล้างไฟล์ที่ไม่ใช้", "Storage full—clean up files"),
  "crash.emergent.oom": entry("หน่วยความจำไม่พอ—แอปต้องการ RAM มากกว่าที่มี", "Out of memory—app needs more RAM than installed"),
  "crash.emergent.bottleneck": entry("คอขวดรุนแรง—อัปเกรดส่วนประกอบที่ช้าที่สุด", "Severe bottleneck—upgrade the slowest component"),

  /* === EDUCATIONAL INSIGHTS / BOTTLENECK TIPS === */
  "tip.title": entry("คำแนะนำแก้ไขคอขวด", "Bottleneck Solution Tips"),
  "tip.cpu": entry("CPU ทำงานหนัก! แนะนำให้เพิ่มจำนวนคอร์ (Cores) หรือความเร็วนาฬิกา (Clock Speed) ในเมนูฮาร์ดแวร์", "CPU is overloaded! Tip: Upgrade CPU cores or clock speed in the Hardware tab."),
  "tip.ram": entry("หน่วยความจำ (RAM) เต็ม! แนะนำให้ปิดบางแอปพลิเคชัน หรืออัปเกรดความจุ RAM ในเมนูฮาร์ดแวร์", "RAM is exhausted! Tip: Close some apps or upgrade RAM capacity in the Hardware tab."),
  "tip.gpu": entry("การ์ดจอ (GPU) รับงานหนัก! แนะนำให้เพิ่มจํานวนคอร์ GPU หรือ VRAM ในเมนูฮาร์ดแวร์", "GPU is bottlenecked! Tip: Upgrade GPU cores or VRAM in the Hardware tab."),
  "tip.storage_io": entry("การอ่านเขียนดิสก์ช้า! แนะนำให้เพิ่มความเร็ว SSD/HDD ในเมนูฮาร์ดแวร์", "Disk I/O is slow! Tip: Upgrade SSD or HDD speed in the Hardware tab."),
  "tip.thermal": entry("CPU ร้อนจัด! แนะนำให้ลดสเปก CPU ลง หรือเพิ่มความเร็วพัดลม (Fan RPM)", "CPU is overheating! Tip: Reduce CPU load/clock or increase Fan RPM."),
};

export function t(key: string, lang: "th" | "en", mode: "student" | "advanced"): string {
  return LANG[key]?.[lang]?.[mode] ?? key;
}
