export type { SpriteData } from '@/app/(website)/games/phonics/types';
export {
  drawSprite,
  blinkSprite,
  ACC_SPRITES,
  HEAD_ACC_Y_OFFSET,
  AVATAR_NOX_HEAD, AVATAR_MIRA_HEAD, AVATAR_CHIP_HEAD,
  AVATAR_FOX_HEAD, AVATAR_CAT_HEAD, AVATAR_BEAR_HEAD,
  AVATAR_BUNNY_HEAD, AVATAR_PENGUIN_HEAD, AVATAR_ALIEN_HEAD, AVATAR_NINJA_HEAD, AVATAR_ROBOT_HEAD,
  AVATAR_DOG_HEAD, AVATAR_GHOST_HEAD,
  MASCOT_IDLE, MIRA_IDLE, CHIP_IDLE,
  FOX_IDLE, CAT_IDLE, BEAR_IDLE, BUNNY_IDLE, PENGUIN_IDLE, ALIEN_IDLE, NINJA_IDLE, ROBOT_IDLE,
  DOG_IDLE, GHOST_IDLE,
} from '@/app/(website)/games/phonics/sprites';
